### PR TITLE
test: more e2e test coverage - backwards compatibility

### LINKED ISSUE #251: TRUNK SSHNP vs. RELEASE v3.2.0 SSHNPD does not work with a new device name
### Conclusion:

The bug was happening because sshnp wouldn't wait for sync to finish

### Describe the bug

**Summary**
Attempted testing current `trunk SSHNP` against `release 3.2.0 SSHNPD` and test failed. Found out that `release 3.2.0 SSHNPD` is not properly sending the device name to `trunk SSHNP`.

However, if you are using trunk SSHNP vs. release 3.2.0 SSHNPD with a **device name that was already previously shared**, then it will work. On the other hand, using an entirely new device name that was not already shared will always crash.

### Steps to reproduce

Run the `sshnpd` binary on release 3.2.0 with an entirely new device name that was never shared before. Examle: `~/.local/bin/sshnpd -a @smoothalligator -m @jeremy_0 -d 123four -s -u -v`

Run the `sshnp` binary on the latest trunk. Example: ` ~/.local/bin/sshnp -f @jeremy_0 -t @smoothalligator -d 123four -h @tastelessbanana -s id_ed25519.pub -v`

On sshnp, you will get
```
Device "123four" unknown, or username not shared
```

### Expected behavior

TRUNK NP to work with v3.2.0 NPD

### Screenshots

_No response_

### Smartphones

_No response_

### Were you using an atApplication when the bug was found?

_No response_

### Additional context

The naming convention I've created is "sshnp-sshnpd-sshrvd". Example: trunk-release3.2.0-release3.3.0 is testing trunk sshnp and release3.2.0 sshnpd and release3.3.0 sshrvd

Testing trunk-release3.2.0-@rv_am **(FAILED)**: release3.2.0 sshnpd broken
https://github.com/atsign-foundation/sshnoports/actions/runs/5533026008/jobs/10096208608?pr=250

Same test as above but with a device name already shared **(PASSED)**: 
https://gist.github.com/JeremyTubongbanua/8911aa1cb7709542d54e7746275e350e

**Some additional tests I did that are somewhat related to what we are discussing:**

Testing release3.2.0-trunk-@rv_am **(PASSED)**: release 3.2.0 sshnp works against trunk sshnpd
https://github.com/atsign-foundation/sshnoports/actions/runs/5533026008/jobs/10096208827?pr=250
Description of this: Although TRUNK NP does not work with 3.2.0 NPD, the converse does work (3.2.0 NP with TRUNK NPD works).

Testing release3.2.0-release3.2.0-release3.2.0 **(PASSED)**: https://gist.github.com/JeremyTubongbanua/2474f8e8aecabc965da63ca34314db4c

### PR DESCRIPTION
**Pull request by JeremyTubongbanua**
Related to #249 

**- What I did**

- added more e2e test coverage
- local-release3.2.0
- local-release3.3.0
- local-release3.1.2
- release3.2.0-local
- release3.3.0-local
- release3.1.2-local

**- How I did it**

**- How to verify it**

**- Description for the changelog**

closes #251

### CODE REVIEW

**Comment by xavierchanth** [comment]
@JeremyTubongbanua can you also add 3.1.2 against latest? (without removing 3.2.0)

**Comment by xavierchanth** [comment]
Uh oh... the docker container was introduced in 3.2.0 ...

**Comment by JeremyTubongbanua** [comment]
@XavierChanth 3.1.2 NPD and 3.2.0 NPD have the same issue trying to work with Latest NP

3.3.0 NPD works with Latest NP, though.

3.1.2NPD-local = https://github.com/atsign-foundation/sshnoports/actions/runs/5534168124/jobs/10098749981?pr=250

**Comment by xavierchanth** [comment]
Thank you, I will investigate further... I think I know what it is

**Review by xavierchanth — APPROVED** [review]

**Pull request merged**
