### PR TITLE
chore: upgrade dependencies

### PR DESCRIPTION
**Pull request by murali-shris**
**- What I did**
- upgraded dependencies in dart no ports
**- How I did it**
- modified pubspec.yaml
**- How to verify it**
- tests should pass

### CODE REVIEW

**Comment by cpswan** [comment]
@murali-shris some of these were already done in #1347

**Comment by murali-shris** [comment]
@gkc change in this repo have to be published through 
https://pub.dev/packages/noports_core ?

**Comment by murali-shris** [comment]
> @murali-shris some of these were already done in #1347

thanks Chris. I will make the changes only for onboarding cli and at_client

**Comment by gkc** [comment]
> @gkc change in this repo have to be published through https://pub.dev/packages/noports_core ?

Yes only noports_core is published, although we haven't published a new version for a while. (We build the apps and CLIs using relative path dependency to it)

**Review by gkc — APPROVED** [review]

**Pull request merged**
