### PR TITLE
refactor: packages dir

### PR DESCRIPTION
**Pull request by xavierchanth**
**- What I did**

Moved all of sshnoports to the packages/sshnoports

**- How I did it**

**- How to verify it**

It might be easier to start by taking a look at [the branch](https://github.com/atsign-foundation/sshnoports/tree/refactor/packages-dir). 

[Test build in progress](https://github.com/atsign-foundation/sshnoports/actions/runs/5427767717)

----

**N.B.** : Upon merge of this PR, the following redirects need updating:

`getsshnpd.noports.com -> https://raw.githubusercontent.com/atsign-foundation/sshnoports/trunk/packages/sshnoports/scripts/install_sshnpd`

`getsshnp.noports.com -> https://raw.githubusercontent.com/atsign-foundation/sshnoports/trunk/packages/sshnoports/scripts/install_sshnp`

(Both entries need `packages/sshnoports` added to their paths)

**- Description for the changelog**
refactor: packages dir

### CODE REVIEW

**Comment by xavierchanth** [comment]
I messed up a few items in the diff... package-macos-arm64.sh and the README.md were not considered renames... but all of the main package was considered renames :)

**Comment by cconstab** [comment]
I am still not sure about a noports repo...

We have other noports apps in standal9ne repos..

Lorawan demo

AtTalk

Others coming ...

For some reaso. I thought this was more about keeping the Python version away from the Dart version ..


@gkc / @XavierChanth / @cpswan 

Your call

**Comment by gkc** [comment]
@XavierChanth shoukd we merge https://github.com/atsign-foundation/sshnoports/pull/233 first?

**Comment by xavierchanth** [comment]
> @XavierChanth shoukd we merge #233 first?

Yes, I've merged. Will address the merge conflicts

**Comment by xavierchanth** [comment]
Once this is merged, other branches will need to merge trunk into their branches

**Review by gkc — APPROVED** [review]
LGTM

**Comment by gkc** [comment]
@XavierChanth who can update the redirects for `getsshnpd.noports.com` and `getsshnp.noports.com`?

**Comment by xavierchanth** [comment]
Merged, and redirect has been updated

**Pull request merged**
