### PR TITLE
chore: bump paramiko to 3.3.1 in the python management sdk

### PR DESCRIPTION
**Pull request by xavierchanth**
**- What I did**

This increases the paramiko version for the SSHNP Client SDK scripts that I've been working on.

NOT sshnpdpy, I'm leaving that to @Xlin123 to increase and test.

From my investigation, this code isn't affected by the breaking changes in paramiko 3.0.0.

**- How I did it**

**- How to verify it**

CleanShot 2023-08-11 at 13 29 32@2x

I had no issues running my local-to-device script, which uploads the repo via sftp, rebuilds sshnpd from the source, and then restarts the sshnpd service using the new version. (All of this is run through sshnp and a paramiko.SSHClient / paramiko.SFTPClient)

**- Description for the changelog**
chore: bump paramiko to 3.3.1 in the python management sdk

### CODE REVIEW

**Comment by xavierchanth** [comment]
The force push is because I accidentally merged by commit ref rather than merging by branch.

**Comment by cpswan** [comment]
@XavierChanth can you please use poetry to create a requirements.txt that pins to a SHA, and also add pip to dependabot.yml so that we keep it up to date (per #312)

**Comment by xavierchanth** [comment]
> @XavierChanth can you please use poetry to create a requirements.txt that pins to a SHA, and also add pip to dependabot.yml so that we keep it up to date (per #312)

Yes, this library is still experimental and parts of it are incomplete, I was going to do that once I've had time to spend on it again, I just wanted to at least update the requirements.txt based on it as-is

**Comment by cpswan** [comment]
@gkc can you please take a look at this one now that I've stuck my oar in and disbarred myself from being a reviewer

**Comment by xavierchanth** [comment]
So does this allow me to pip install that dir as a package now? @cpswan

**Comment by cpswan** [comment]
@XavierChanth this is a step along the road to making it a PyPi package. But we're not there yet.

All that's happening so far is we've defined a `pyproject.toml` so that poetry can generate a `reqirements.txt` with deps pinned to SHAs.

The metadata in that toml file is what we'd use for publishing to PyPi, but we're waiting on getting an org account set up (and account creation is in a parlous state right now due to [bad actors](https://www.theregister.com/2023/05/22/python_package_index_on_call/)).

**Review by gkc — APPROVED** [review]

**Pull request merged**
