### PR TITLE
ci: e2e tests for the installer

### LINKED ISSUE #317: SSH No Ports: E2E Test - Installer Script
End-to-end test where we use the installer script to install latest release of ssh no ports and then use the installed binaries and generated custom scripts to test basic functionality of SSH No ports with prod atSigns

### PR DESCRIPTION
**Pull request by xavierchanth**
closes #317 

**- What I did**

Working on e2e tests so we can comfortably merge #320 

Added end2end tests that test the sshnp and sshnpd installers against local and trunk.

Updated the sshnp and sshnpd installers in order to get it running on the debian slim test image, had to cut back on certain shell features which weren't available in the slim environment.

On the sshnp side, it does not test the custom script, I will think about doing a later update once the newer script template is released, since the newer script template allows passing custom args to sshnp.

On the sshnpd side, it tests the custom script, but doesn't test the job used to install the script (i.e. with cron/tmux/etc.).

This is a start, there is room for improvement but it is good enough for now.

**- How I did it**

**- How to verify it**

**- Description for the changelog**
ci: e2e tests for the installer

### CODE REVIEW

**Comment by xavierchanth** [comment]
It seems that the slim environment is unhappy with some of the shell syntax used in the install scripts, might take a bit longer than expected to get them working

**Comment by xavierchanth** [comment]
I remember going with some of these solutions before, and shell check recommending a different approach... where it would prefer the cleaner solution which works 90% of the time instead of the dirty 99% solution.

**Comment by xavierchanth** [comment]
The installer - installer test seems to not be running anything, @JeremyTubongbanua maybe you have some insight into what I did wrong?

**Comment by JeremyTubongbanua** [comment]
My only feedback would be to just create a whole new template like "sshnp_installer_entrypoint.sh" then when we copy it over into the context, make sure it's named "entrypoint.sh" 

Like
```sh
cp /../sshnp_installer_entrypoint.sh /../entrypoint.sh
```

**Review by JeremyTubongbanua — DISMISSED** [review]

**Comment by xavierchanth** [comment]
> My only feedback would be to just create a whole new template like "sshnp_installer_entrypoint.sh" then when we copy it over into the context, make sure it's named "entrypoint.sh" 
> 
> 
> 
> Like
> 
> ```sh
> 
> cp /../sshnp_installer_entrypoint.sh /../entrypoint.sh
> 
> ```

Could do, but most of the logic is the same, so I introduced the USE_INSTALLER environment variable to deal with the few differences.

**Comment by JeremyTubongbanua** [comment]
> > My only feedback would be to just create a whole new template like "sshnp_installer_entrypoint.sh" then when we copy it over into the context, make sure it's named "entrypoint.sh"
> > Like
> > ```shell
> > cp /../sshnp_installer_entrypoint.sh /../entrypoint.sh
> > ```
> 
> Could do, but most of the logic is the same, so I introduced the USE_INSTALLER environment variable to deal with the few differences.

Cause when we add more tests, it'll fill up the sshnpX_entrypoint.sh

**Comment by xavierchanth** [comment]
> > > My only feedback would be to just create a whole new template like "sshnp_installer_entrypoint.sh" then when we copy it over into the context, make sure it's named "entrypoint.sh"
> 
> > > Like
> 
> > > ```shell
> 
> > > cp /../sshnp_installer_entrypoint.sh /../entrypoint.sh
> 
> > > ```
> 
> > 
> 
> > Could do, but most of the logic is the same, so I introduced the USE_INSTALLER environment variable to deal with the few differences.
> 
> 
> 
> Cause when we add more tests, it'll fill up the sshnpX_entrypoint.sh

Ah, makes sense

**Comment by xavierchanth** [comment]
@JeremyTubongbanua I'll need a reapproval, feel free to merge if you are happy with the changes.

**Comment by xavierchanth** [comment]
I made it so that the composite action controls the name of the entrypoint template file to use

`.github/composite/setup_entrypoints/action.yaml`

**Comment by xavierchanth** [comment]
Please squash when you merge this PR!

**Review by JeremyTubongbanua — APPROVED** [review]

**Pull request merged**
