### PR TITLE
build: exclude policy admin webapp assets from the docker distributions

### PR DESCRIPTION
**Pull request by gkc**
**- What I did**
- build: include policy admin API but exclude policy admin webapp assets from the docker distributions
- Context: (a) installing node slows down the dockerfile build quite a lot; (b) required version of node is not available as standard (i.e. via apt-get) for the platforms in question so can't (currently) build the webapp anyway (c) if required, the webapp assets can be copied from other downloads

**- How I did it**
- Removed the node install and npm build steps from tools/multibuild/Dockerfile.package
- Additionally, although unrelated, now specifying npm version to use when building the webapp assets in multibuild.yaml main_build

**- How to verify it**
Manually verified by running multibuild workflow against this branch - see https://github.com/atsign-foundation/noports/actions/runs/11878280981/job/33098772780

### CODE REVIEW

**Review by xavierchanth — APPROVED** [review]

**Comment by xavierchanth** [comment]
We can always offer a second docker image for the web app and provide an example compose file of how to run both. Although, they have no internal dependencies so there's no special configuration, they just need the same atsign.

**Review by cpswan — APPROVED** [review]

**Comment by gkc** [comment]
> We can always offer a second docker image for the web app and provide an example compose file of how to run both. Although, they have no internal dependencies so there's no special configuration, they just need the same atsign.

@XavierChanth yes; also could copy the web assets into the docker file from a pre-docker-file-build step

**Comment by xavierchanth** [comment]
> > We can always offer a second docker image for the web app and provide an example compose file of how to run both. Although, they have no internal dependencies so there's no special configuration, they just need the same atsign.
> 
> @XavierChanth yes; also could copy the web assets into the docker file from a pre-docker-file-build step

I wasn't planning on working on it until we have an ask.

**Comment by cpswan** [comment]
I can take a look at this.

**Pull request merged**
