### PR TITLE
fix: When running npt in keep-alive mode then the keep-alive loop should never exit due to an exception from `npt.run()`

### LINKED ISSUE #1182: NPT in "daemon mode" (-K -T) can crash with bad network/other conditions
### Describe the bug

NPT can crash hard so needs to be run as a service/loop

### Steps to reproduce

1. Set up a long term npt session with -K -T
2. Wait 
3. Eventually it may crash

### Expected behavior

No crash just a restart

### Screenshots

```
{"devicename":"orac","version":"5.3.0","corePackageVersion":"6.1.0","supportedFeatures":{"srAuth":true,"srE2ee":true,"acceptsPublicKeys":false,"supportsPortChoice":true,"adjustableTimeout":true},"allowedServices":["localhost:22","localhost:5201","192.168.1.90:445","192.168.1.90:139"]}
INFO|2024-07-03 23:11:07.908578| SshnpdChannel |Received ping response from @ssh_1 : @cconstab:heartbeat.orac.sshnp@ssh_1 : {"devicename":"orac","version":"5.3.0","corePackageVersion":"6.1.0","supportedFeatures":{"srAuth":true,"srE2ee":true,"acceptsPublicKeys":false,"supportsPortChoice":true,"adjustableTimeout":true},"allowedServices":["localhost:22","localhost:5201","192.168.1.90:445","192.168.1.90:139"]}
INFO|2024-07-03 23:11:07.908578| SshnpdChannel |Received ping response from @ssh_1 : @cconstab:heartbeat.orac.sshnp@ssh_1 : {"devicename":"orac","version":"5.3.0","corePackageVersion":"6.1.0","supportedFeatures":{"srAuth":true,"srE2ee":true,"acceptsPublicKeys":false,"supportsPortChoice":true,"adjustableTimeout":true},"allowedServices":["localhost:22","localhost:5201","192.168.1.90:445","192.168.1.90:139"]}
INFO|2024-07-03 23:11:07.908578| SshnpdChannel |Received ping response from @ssh_1 : @cconstab:heartbeat.orac.sshnp@ssh_1 : {"devicename":"orac","version":"5.3.0","corePackageVersion":"6.1.0","supportedFeatures":{"srAuth":true,"srE2ee":true,"acceptsPublicKeys":false,"supportsPortChoice":true,"adjustableTimeout":true},"allowedServices":["localhost:22","localhost:5201","192.168.1.90:445","192.168.1.90:139"]}
INFO|2024-07-03 23:11:07.908578| SshnpdChannel |Received ping response from @ssh_1 : @cconstab:heartbeat.orac.sshnp@ssh_1 : {"devicename":"orac","version":"5.3.0","corePackageVersion":"6.1.0","supportedFeatures":{"srAuth":true,"srE2ee":true,"acceptsPublicKeys":false,"supportsPortChoice":true,"adjustableTimeout":true},"allowedServices":["localhost:22","localhost:5201","192.168.1.90:445","192.168.1.90:139"]}
INFO|2024-07-03 23:11:07.908578| SshnpdChannel |Completing the future
INFO|2024-07-03 23:11:09.310954| SrvdChannel |Still waiting for srvd response
INFO|2024-07-03 23:11:11.475119| SrvdChannel |Still waiting for srvd response
INFO|2024-07-03 23:11:13.655144| SrvdChannel |Still waiting for srvd response
INFO|2024-07-03 23:11:15.816416| SrvdChannel |Still waiting for srvd response
INFO|2024-07-03 23:11:17.983360| SrvdChannel |Still waiting for srvd response
INFO|2024-07-03 23:11:20.151255| SrvdChannel |Still waiting for srvd response
INFO|2024-07-03 23:11:22.330202| SrvdChannel |Still waiting for srvd response
WARNING|2024-07-03 23:11:23.518983| SrvdChannel |Timed out waiting for srvd response
INFO|2024-07-03 23:11:28.526511| Npt |Initializing _NptImpl
INFO|2024-07-03 23:11:28.526511| SshnpdChannel |Starting monitor for notifications with regex: "48d7a842-a336-4b0d-9e2a-101a48215061.orac.sshnp@ssh_1"
INFO|2024-07-03 23:11:28.526511| SshnpdChannel |Subscribing to notifications with regex: "48d7a842-a336-4b0d-9e2a-101a48215061.orac.sshnp@ssh_1"
INFO|2024-07-03 23:11:28.527049| Npt |Sending daemon feature check request
INFO|2024-07-03 23:11:28.527049| SshnpdChannel |Subscribing to notifications with regex: "heartbeat.orac.sshnp"
INFO|2024-07-03 23:11:28.527049| SshnpdChannel |Sending ping to sshnpd
INFO|2024-07-03 23:11:28.527049| SrvdChannel |Subscribing to notifications with regex: "48d7a842-a336-4b0d-9e2a-101a48215061.sshrvd@"
INFO|2024-07-03 23:11:28.527049| SrvdChannel |Started listening for srvd response
INFO|2024-07-03 23:11:28.527049| SrvdChannel |Sending notification to srvd with key @stream:orac.request_ports.sshrvd@cconstab and value {"sessionId":"48d7a842-a336-4b0d-9e2a-101a48215061","atSignA":"@cconstab","atSignB":"@ssh_1","authenticateSocketA":true,"authenticateSocketB":true,"clientNonce":"2024-07-03T23:11:28.526511"}
INFO|2024-07-03 23:11:29.345701| SshnpdChannel |Received ping response from @ssh_1 : @cconstab:heartbeat.orac.sshnp@ssh_1 : {"devicename":"orac","version":"5.3.0","corePackageVersion":"6.1.0","supportedFeatures":{"srAuth":true,"srE2ee":true,"acceptsPublicKeys":false,"supportsPortChoice":true,"adjustableTimeout":true},"allowedServices":["localhost:22","localhost:5201","192.168.1.90:445","192.168.1.90:139"]}
INFO|2024-07-03 23:11:29.345701| SshnpdChannel |Received ping response from @ssh_1 : @cconstab:heartbeat.orac.sshnp@ssh_1 : {"devicename":"orac","version":"5.3.0","corePackageVersion":"6.1.0","supportedFeatures":{"srAuth":true,"srE2ee":true,"acceptsPublicKeys":false,"supportsPortChoice":true,"adjustableTimeout":true},"allowedServices":["localhost:22","localhost:5201","192.168.1.90:445","192.168.1.90:139"]}
INFO|2024-07-03 23:11:29.345701| SshnpdChannel |Received ping response from @ssh_1 : @cconstab:heartbeat.orac.sshnp@ssh_1 : {"devicename":"orac","version":"5.3.0","corePackageVersion":"6.1.0","supportedFeatures":{"srAuth":true,"srE2ee":true,"acceptsPublicKeys":false,"supportsPortChoice":true,"adjustableTimeout":true},"allowedServices":["localhost:22","localhost:5201","192.168.1.90:445","192.168.1.90:139"]}
INFO|2024-07-03 23:11:29.346705| SshnpdChannel |Received ping response from @ssh_1 : @cconstab:heartbeat.orac.sshnp@ssh_1 : {"devicename":"orac","version":"5.3.0","corePackageVersion":"6.1.0","supportedFeatures":{"srAuth":true,"srE2ee":true,"acceptsPublicKeys":false,"supportsPortChoice":true,"adjustableTimeout":true},"allowedServices":["localhost:22","localhost:5201","192.168.1.90:445","192.168.1.90:139"]}
INFO|2024-07-03 23:11:29.346705| SshnpdChannel |Received ping response from @ssh_1 : @cconstab:heartbeat.orac.sshnp@ssh_1 : {"devicename":"orac","version":"5.3.0","corePackageVersion":"6.1.0","supportedFeatures":{"srAuth":true,"srE2ee":true,"acceptsPublicKeys":false,"supportsPortChoice":true,"adjustableTimeout":true},"allowedServices":["localhost:22","localhost:5201","192.168.1.90:445","192.168.1.90:139"]}
INFO|2024-07-03 23:11:29.346705| SshnpdChannel |Received ping response from @ssh_1 : @cconstab:heartbeat.orac.sshnp@ssh_1 : {"devicename":"orac","version":"5.3.0","corePackageVersion":"6.1.0","supportedFeatures":{"srAuth":true,"srE2ee":true,"acceptsPublicKeys":false,"supportsPortChoice":true,"adjustableTimeout":true},"allowedServices":["localhost:22","localhost:5201","192.168.1.90:445","192.168.1.90:139"]}
INFO|2024-07-03 23:11:29.346705| SshnpdChannel |Received ping response from @ssh_1 : @cconstab:heartbeat.orac.sshnp@ssh_1 : {"devicename":"orac","version":"5.3.0","corePackageVersion":"6.1.0","supportedFeatures":{"srAuth":true,"srE2ee":true,"acceptsPublicKeys":false,"supportsPortChoice":true,"adjustableTimeout":true},"allowedServices":["localhost:22","localhost:5201","192.168.1.90:445","192.168.1.90:139"]}
INFO|2024-07-03 23:11:29.346705| SshnpdChannel |Received ping response from @ssh_1 : @cconstab:heartbeat.orac.sshnp@ssh_1 : {"devicename":"orac","version":"5.3.0","corePackageVersion":"6.1.0","supportedFeatures":{"srAuth":true,"srE2ee":true,"acceptsPublicKeys":false,"supportsPortChoice":true,"adjustableTimeout":true},"allowedServices":["localhost:22","localhost:5201","192.168.1.90:445","192.168.1.90:139"]}
INFO|2024-07-03 23:11:29.346705| SshnpdChannel |Received ping response from @ssh_1 : @cconstab:heartbeat.orac.sshnp@ssh_1 : {"devicename":"orac","version":"5.3.0","corePackageVersion":"6.1.0","supportedFeatures":{"srAuth":true,"srE2ee":true,"acceptsPublicKeys":false,"supportsPortChoice":true,"adjustableTimeout":true},"allowedServices":["localhost:22","localhost:5201","192.168.1.90:445","192.168.1.90:139"]}
INFO|2024-07-03 23:11:29.346705| SshnpdChannel |Received ping response from @ssh_1 : @cconstab:heartbeat.orac.sshnp@ssh_1 : {"devicename":"orac","version":"5.3.0","corePackageVersion":"6.1.0","supportedFeatures":{"srAuth":true,"srE2ee":true,"acceptsPublicKeys":false,"supportsPortChoice":true,"adjustableTimeout":true},"allowedServices":["localhost:22","localhost:5201","192.168.1.90:445","192.168.1.90:139"]}
INFO|2024-07-03 23:11:29.346705| SshnpdChannel |Completing the future
INFO|2024-07-03 23:11:30.999742| SrvdChannel |Still waiting for srvd response
INFO|2024-07-03 23:11:33.161172| SrvdChannel |Still waiting for srvd response
INFO|2024-07-03 23:11:35.332587| SrvdChannel |Still waiting for srvd response
INFO|2024-07-03 23:11:37.502107| SrvdChannel |Still waiting for srvd response
INFO|2024-07-03 23:11:39.663366| SrvdChannel |Still waiting for srvd response
INFO|2024-07-03 23:11:41.830362| SrvdChannel |Still waiting for srvd response
INFO|2024-07-03 23:11:44.009387| SrvdChannel |Still waiting for srvd response
WARNING|2024-07-03 23:11:45.203390| SrvdChannel |Timed out waiting for srvd response
INFO|2024-07-03 23:11:50.207681| Npt |Initializing _NptImpl
INFO|2024-07-03 23:11:50.207681| SshnpdChannel |Starting monitor for notifications with regex: "e9548175-33f5-4018-84aa-5637fbc005b7.orac.sshnp@ssh_1"
INFO|2024-07-03 23:11:50.207681| SshnpdChannel |Subscribing to notifications with regex: "e9548175-33f5-4018-84aa-5637fbc005b7.orac.sshnp@ssh_1"
INFO|2024-07-03 23:11:50.207681| Npt |Sending daemon feature check request
INFO|2024-07-03 23:11:50.207681| SshnpdChannel |Subscribing to notifications with regex: "heartbeat.orac.sshnp"
INFO|2024-07-03 23:11:50.207681| SshnpdChannel |Sending ping to sshnpd
INFO|2024-07-03 23:11:50.207681| SrvdChannel |Subscribing to notifications with regex: "e9548175-33f5-4018-84aa-5637fbc005b7.sshrvd@"
INFO|2024-07-03 23:11:50.208679| SrvdChannel |Started listening for srvd response
INFO|2024-07-03 23:11:50.208679| SrvdChannel |Sending notification to srvd with key @stream:orac.request_ports.sshrvd@cconstab and value {"sessionId":"e9548175-33f5-4018-84aa-5637fbc005b7","atSignA":"@cconstab","atSignB":"@ssh_1","authenticateSocketA":true,"authenticateSocketB":true,"clientNonce":"2024-07-03T23:11:50.207681"}
INFO|2024-07-03 23:11:51.215716| SshnpdChannel |Received ping response from @ssh_1 : @cconstab:heartbeat.orac.sshnp@ssh_1 : {"devicename":"orac","version":"5.3.0","corePackageVersion":"6.1.0","supportedFeatures":{"srAuth":true,"srE2ee":true,"acceptsPublicKeys":false,"supportsPortChoice":true,"adjustableTimeout":true},"allowedServices":["localhost:22","localhost:5201","192.168.1.90:445","192.168.1.90:139"]}
INFO|2024-07-03 23:11:51.215716| SshnpdChannel |Received ping response from @ssh_1 : @cconstab:heartbeat.orac.sshnp@ssh_1 : {"devicename":"orac","version":"5.3.0","corePackageVersion":"6.1.0","supportedFeatures":{"srAuth":true,"srE2ee":true,"acceptsPublicKeys":false,"supportsPortChoice":true,"adjustableTimeout":true},"allowedServices":["localhost:22","localhost:5201","192.168.1.90:445","192.168.1.90:139"]}
INFO|2024-07-03 23:11:51.215716| SshnpdChannel |Received ping response from @ssh_1 : @cconstab:heartbeat.orac.sshnp@ssh_1 : {"devicename":"orac","version":"5.3.0","corePackageVersion":"6.1.0","supportedFeatures":{"srAuth":true,"srE2ee":true,"acceptsPublicKeys":false,"supportsPortChoice":true,"adjustableTimeout":true},"allowedServices":["localhost:22","localhost:5201","192.168.1.90:445","192.168.1.90:139"]}
INFO|2024-07-03 23:11:51.215716| SshnpdChannel |Received ping response from @ssh_1 : @cconstab:heartbeat.orac.sshnp@ssh_1 : {"devicename":"orac","version":"5.3.0","corePackageVersion":"6.1.0","supportedFeatures":{"srAuth":true,"srE2ee":true,"acceptsPublicKeys":false,"supportsPortChoice":true,"adjustableTimeout":true},"allowedServices":["localhost:22","localhost:5201","192.168.1.90:445","192.168.1.90:139"]}
INFO|2024-07-03 23:11:51.216716| SshnpdChannel |Received ping response from @ssh_1 : @cconstab:heartbeat.orac.sshnp@ssh_1 : {"devicename":"orac","version":"5.3.0","corePackageVersion":"6.1.0","supportedFeatures":{"srAuth":true,"srE2ee":true,"acceptsPublicKeys":false,"supportsPortChoice":true,"adjustableTimeout":true},"allowedServices":["localhost:22","localhost:5201","192.168.1.90:445","192.168.1.90:139"]}
INFO|2024-07-03 23:11:51.216716| SshnpdChannel |Received ping response from @ssh_1 : @cconstab:heartbeat.orac.sshnp@ssh_1 : {"devicename":"orac","version":"5.3.0","corePackageVersion":"6.1.0","supportedFeatures":{"srAuth":true,"srE2ee":true,"acceptsPublicKeys":false,"supportsPortChoice":true,"adjustableTimeout":true},"allowedServices":["localhost:22","localhost:5201","192.168.1.90:445","192.168.1.90:139"]}
INFO|2024-07-03 23:11:51.216716| SshnpdChannel |Received ping response from @ssh_1 : @cconstab:heartbeat.orac.sshnp@ssh_1 : {"devicename":"orac","version":"5.3.0","corePackageVersion":"6.1.0","supportedFeatures":{"srAuth":true,"srE2ee":true,"acceptsPublicKeys":false,"supportsPortChoice":true,"adjustableTimeout":true},"allowedServices":["localhost:22","localhost:5201","192.168.1.90:445","192.168.1.90:139"]}
INFO|2024-07-03 23:11:51.216716| SshnpdChannel |Received ping response from @ssh_1 : @cconstab:heartbeat.orac.sshnp@ssh_1 : {"devicename":"orac","version":"5.3.0","corePackageVersion":"6.1.0","supportedFeatures":{"srAuth":true,"srE2ee":true,"acceptsPublicKeys":false,"supportsPortChoice":true,"adjustableTimeout":true},"allowedServices":["localhost:22","localhost:5201","192.168.1.90:445","192.168.1.90:139"]}
INFO|2024-07-03 23:11:51.216716| SshnpdChannel |Received ping response from @ssh_1 : @cconstab:heartbeat.orac.sshnp@ssh_1 : {"devicename":"orac","version":"5.3.0","corePackageVersion":"6.1.0","supportedFeatures":{"srAuth":true,"srE2ee":true,"acceptsPublicKeys":false,"supportsPortChoice":true,"adjustableTimeout":true},"allowedServices":["localhost:22","localhost:5201","192.168.1.90:445","192.168.1.90:139"]}
INFO|2024-07-03 23:11:51.216716| SshnpdChannel |Received ping response from @ssh_1 : @cconstab:heartbeat.orac.sshnp@ssh_1 : {"devicename":"orac","version":"5.3.0","corePackageVersion":"6.1.0","supportedFeatures":{"srAuth":true,"srE2ee":true,"acceptsPublicKeys":false,"supportsPortChoice":true,"adjustableTimeout":true},"allowedServices":["localhost:22","localhost:5201","192.168.1.90:445","192.168.1.90:139"]}
INFO|2024-07-03 23:11:51.216716| SshnpdChannel |Received ping response from @ssh_1 : @cconstab:heartbeat.orac.sshnp@ssh_1 : {"devicename":"orac","version":"5.3.0","corePackageVersion":"6.1.0","supportedFeatures":{"srAuth":true,"srE2ee":true,"acceptsPublicKeys":false,"supportsPortChoice":true,"adjustableTimeout":true},"allowedServices":["localhost:22","localhost:5201","192.168.1.90:445","192.168.1.90:139"]}
INFO|2024-07-03 23:11:51.216716| SshnpdChannel |Completing the future
INFO|2024-07-03 23:11:52.713116| SrvdChannel |Still waiting for srvd response
INFO|2024-07-03 23:11:54.867924| SrvdChannel |Still waiting for srvd response
INFO|2024-07-03 23:11:57.046532| SrvdChannel |Still waiting for srvd response
INFO|2024-07-03 23:11:59.205076| SrvdChannel |Still waiting for srvd response
INFO|2024-07-03 23:12:01.373072| SrvdChannel |Still waiting for srvd response
INFO|2024-07-03 23:12:03.533834| SrvdChannel |Still waiting for srvd response
INFO|2024-07-03 23:12:05.716307| SrvdChannel |Still waiting for srvd response
WARNING|2024-07-03 23:12:06.903338| SrvdChannel |Timed out waiting for srvd response
INFO|2024-07-03 23:12:11.884668| SrvdChannel |Received from srvd: 85.239.53.170,46123,44007,2024-07-04T06:12:10.792736
INFO|2024-07-03 23:12:11.884668| SrvdChannel |Received from srvd: rvdHost:clientPort:daemonPort 85.239.53.170:46123:44007 rvdNonce: 2024-07-04T06:12:10.792736
INFO|2024-07-03 23:12:11.884668| SrvdChannel |Daemon will connect to: 85.239.53.170:44007
INFO|2024-07-03 23:12:11.913670| Npt |Initializing _NptImpl
INFO|2024-07-03 23:12:11.913670| SshnpdChannel |Starting monitor for notifications with regex: "a743761e-15fb-4b5a-8f62-6d24f29a906a.orac.sshnp@ssh_1"
INFO|2024-07-03 23:12:11.913670| SshnpdChannel |Subscribing to notifications with regex: "a743761e-15fb-4b5a-8f62-6d24f29a906a.orac.sshnp@ssh_1"
INFO|2024-07-03 23:12:11.913670| Npt |Sending daemon feature check request
INFO|2024-07-03 23:12:11.913670| SshnpdChannel |Subscribing to notifications with regex: "heartbeat.orac.sshnp"
INFO|2024-07-03 23:12:11.913670| SshnpdChannel |Sending ping to sshnpd
INFO|2024-07-03 23:12:11.913670| SrvdChannel |Subscribing to notifications with regex: "a743761e-15fb-4b5a-8f62-6d24f29a906a.sshrvd@"
INFO|2024-07-03 23:12:11.913670| SrvdChannel |Started listening for srvd response
INFO|2024-07-03 23:12:11.914669| SrvdChannel |Sending notification to srvd with key @stream:orac.request_ports.sshrvd@cconstab and value {"sessionId":"a743761e-15fb-4b5a-8f62-6d24f29a906a","atSignA":"@cconstab","atSignB":"@ssh_1","authenticateSocketA":true,"authenticateSocketB":true,"clientNonce":"2024-07-03T23:12:11.913670"}
INFO|2024-07-03 23:12:14.925174| SrvdChannel |Received from srvd: 85.239.53.170,41685,37761,2024-07-04T06:12:11.011350
INFO|2024-07-03 23:12:14.925174| SrvdChannel |Received from srvd: rvdHost:clientPort:daemonPort 85.239.53.170:41685:37761 rvdNonce: 2024-07-04T06:12:11.011350
INFO|2024-07-03 23:12:14.925174| SrvdChannel |Daemon will connect to: 85.239.53.170:37761
INFO|2024-07-03 23:12:16.662764| SrvdChannel |Received from srvd: 85.239.53.170,34639,39499,2024-07-04T06:12:10.847263
INFO|2024-07-03 23:12:16.662764| SrvdChannel |Received from srvd: rvdHost:clientPort:daemonPort 85.239.53.170:34639:39499 rvdNonce: 2024-07-04T06:12:10.847263
INFO|2024-07-03 23:12:16.662764| SrvdChannel |Daemon will connect to: 85.239.53.170:39499
INFO|2024-07-03 23:12:19.462414| SrvdChannel |Received from srvd: 85.239.53.170,33897,40463,2024-07-04T06:12:11.067460
INFO|2024-07-03 23:12:19.462414| SrvdChannel |Received from srvd: rvdHost:clientPort:daemonPort 85.239.53.170:33897:40463 rvdNonce: 2024-07-04T06:12:11.067460
INFO|2024-07-03 23:12:19.462414| SrvdChannel |Daemon will connect to: 85.239.53.170:40463
INFO|2024-07-03 23:12:20.977929| SrvdChannel |Received from srvd: 85.239.53.170,39803,33515,2024-07-04T06:12:10.902363
INFO|2024-07-03 23:12:20.977929| SrvdChannel |Received from srvd: rvdHost:clientPort:daemonPort 85.239.53.170:39803:33515 rvdNonce: 2024-07-04T06:12:10.902363
INFO|2024-07-03 23:12:20.977929| SrvdChannel |Daemon will connect to: 85.239.53.170:33515
INFO|2024-07-03 23:12:23.668531| SrvdChannel |Received from srvd: 85.239.53.170,46461,44357,2024-07-04T06:12:10.957013
INFO|2024-07-03 23:12:23.669529| SrvdChannel |Received from srvd: rvdHost:clientPort:daemonPort 85.239.53.170:46461:44357 rvdNonce: 2024-07-04T06:12:10.957013
INFO|2024-07-03 23:12:23.669529| SrvdChannel |Daemon will connect to: 85.239.53.170:44357
INFO|2024-07-03 23:12:27.344943| SshnpdChannel |Received ping response from @ssh_1 : @cconstab:heartbeat.orac.sshnp@ssh_1 : {"devicename":"orac","version":"5.3.0","corePackageVersion":"6.1.0","supportedFeatures":{"srAuth":true,"srE2ee":true,"acceptsPublicKeys":false,"supportsPortChoice":true,"adjustableTimeout":true},"allowedServices":["localhost:22","localhost:5201","192.168.1.90:445","192.168.1.90:139"]}
INFO|2024-07-03 23:12:27.344943| SshnpdChannel |Received ping response from @ssh_1 : @cconstab:heartbeat.orac.sshnp@ssh_1 : {"devicename":"orac","version":"5.3.0","corePackageVersion":"6.1.0","supportedFeatures":{"srAuth":true,"srE2ee":true,"acceptsPublicKeys":false,"supportsPortChoice":true,"adjustableTimeout":true},"allowedServices":["localhost:22","localhost:5201","192.168.1.90:445","192.168.1.90:139"]}
INFO|2024-07-03 23:12:27.344943| SshnpdChannel |Received ping response from @ssh_1 : @cconstab:heartbeat.orac.sshnp@ssh_1 : {"devicename":"orac","version":"5.3.0","corePackageVersion":"6.1.0","supportedFeatures":{"srAuth":true,"srE2ee":true,"acceptsPublicKeys":false,"supportsPortChoice":true,"adjustableTimeout":true},"allowedServices":["localhost:22","localhost:5201","192.168.1.90:445","192.168.1.90:139"]}
INFO|2024-07-03 23:12:27.344943| SshnpdChannel |Received ping response from @ssh_1 : @cconstab:heartbeat.orac.sshnp@ssh_1 : {"devicename":"orac","version":"5.3.0","corePackageVersion":"6.1.0","supportedFeatures":{"srAuth":true,"srE2ee":true,"acceptsPublicKeys":false,"supportsPortChoice":true,"adjustableTimeout":true},"allowedServices":["localhost:22","localhost:5201","192.168.1.90:445","192.168.1.90:139"]}
INFO|2024-07-03 23:12:27.345944| SshnpdChannel |Received ping response from @ssh_1 : @cconstab:heartbeat.orac.sshnp@ssh_1 : {"devicename":"orac","version":"5.3.0","corePackageVersion":"6.1.0","supportedFeatures":{"srAuth":true,"srE2ee":true,"acceptsPublicKeys":false,"supportsPortChoice":true,"adjustableTimeout":true},"allowedServices":["localhost:22","localhost:5201","192.168.1.90:445","192.168.1.90:139"]}
INFO|2024-07-03 23:12:27.345944| SshnpdChannel |Received ping response from @ssh_1 : @cconstab:heartbeat.orac.sshnp@ssh_1 : {"devicename":"orac","version":"5.3.0","corePackageVersion":"6.1.0","supportedFeatures":{"srAuth":true,"srE2ee":true,"acceptsPublicKeys":false,"supportsPortChoice":true,"adjustableTimeout":true},"allowedServices":["localhost:22","localhost:5201","192.168.1.90:445","192.168.1.90:139"]}
INFO|2024-07-03 23:12:27.345944| SshnpdChannel |Received ping response from @ssh_1 : @cconstab:heartbeat.orac.sshnp@ssh_1 : {"devicename":"orac","version":"5.3.0","corePackageVersion":"6.1.0","supportedFeatures":{"srAuth":true,"srE2ee":true,"acceptsPublicKeys":false,"supportsPortChoice":true,"adjustableTimeout":true},"allowedServices":["localhost:22","localhost:5201","192.168.1.90:445","192.168.1.90:139"]}
INFO|2024-07-03 23:12:27.345944| SshnpdChannel |Received ping response from @ssh_1 : @cconstab:heartbeat.orac.sshnp@ssh_1 : {"devicename":"orac","version":"5.3.0","corePackageVersion":"6.1.0","supportedFeatures":{"srAuth":true,"srE2ee":true,"acceptsPublicKeys":false,"supportsPortChoice":true,"adjustableTimeout":true},"allowedServices":["localhost:22","localhost:5201","192.168.1.90:445","192.168.1.90:139"]}
INFO|2024-07-03 23:12:27.345944| SshnpdChannel |Received ping response from @ssh_1 : @cconstab:heartbeat.orac.sshnp@ssh_1 : {"devicename":"orac","version":"5.3.0","corePackageVersion":"6.1.0","supportedFeatures":{"srAuth":true,"srE2ee":true,"acceptsPublicKeys":false,"supportsPortChoice":true,"adjustableTimeout":true},"allowedServices":["localhost:22","localhost:5201","192.168.1.90:445","192.168.1.90:139"]}
INFO|2024-07-03 23:12:27.345944| SshnpdChannel |Received ping response from @ssh_1 : @cconstab:heartbeat.orac.sshnp@ssh_1 : {"devicename":"orac","version":"5.3.0","corePackageVersion":"6.1.0","supportedFeatures":{"srAuth":true,"srE2ee":true,"acceptsPublicKeys":false,"supportsPortChoice":true,"adjustableTimeout":true},"allowedServices":["localhost:22","localhost:5201","192.168.1.90:445","192.168.1.90:139"]}
INFO|2024-07-03 23:12:27.345944| SshnpdChannel |Received ping response from @ssh_1 : @cconstab:heartbeat.orac.sshnp@ssh_1 : {"devicename":"orac","version":"5.3.0","corePackageVersion":"6.1.0","supportedFeatures":{"srAuth":true,"srE2ee":true,"acceptsPublicKeys":false,"supportsPortChoice":true,"adjustableTimeout":true},"allowedServices":["localhost:22","localhost:5201","192.168.1.90:445","192.168.1.90:139"]}
INFO|2024-07-03 23:12:27.345944| SshnpdChannel |Received ping response from @ssh_1 : @cconstab:heartbeat.orac.sshnp@ssh_1 : {"devicename":"orac","version":"5.3.0","corePackageVersion":"6.1.0","supportedFeatures":{"srAuth":true,"srE2ee":true,"acceptsPublicKeys":false,"supportsPortChoice":true,"adjustableTimeout":true},"allowedServices":["localhost:22","localhost:5201","192.168.1.90:445","192.168.1.90:139"]}
INFO|2024-07-03 23:12:27.346953| SshnpdChannel |Completing the future
INFO|2024-07-03 23:12:28.263446| SrvdChannel |Still waiting for srvd response
INFO|2024-07-03 23:12:30.424340| SrvdChannel |Still waiting for srvd response
INFO|2024-07-03 23:12:32.023855| SrvdChannel |Received from srvd: 85.239.53.170,44281,44841,2024-07-04T06:12:28.297290
INFO|2024-07-03 23:12:32.023855| SrvdChannel |Received from srvd: rvdHost:clientPort:daemonPort 85.239.53.170:44281:44841 rvdNonce: 2024-07-04T06:12:28.297290
INFO|2024-07-03 23:12:32.023855| SrvdChannel |Daemon will connect to: 85.239.53.170:44841
INFO|2024-07-03 23:12:32.051863| Npt |Sending session request to the device daemon
INFO|2024-07-03 23:12:34.957353| SshnpdChannel |Received a743761e-15fb-4b5a-8f62-6d24f29a906a.orac.sshnp@ssh_1 notification
SHOUT|2024-07-03 23:12:34.957353| SshnpdChannel |invalid daemon response: Failed to start up the daemon side of the srv socket tunnel : SHOUT|2024-07-03 23:12:34.599810| srv.main |Exception running srv : SocketException: Connection timed out, host: 85.239.53.170, port: 44841
INFO|2024-07-03 23:12:35.078631| SshnpdChannel |sshnpdAck: SshnpdAck.acknowledgedWithErrors

Error : Received error response from the device daemon

Stack Trace: #0      _NptImpl.run (package:noports_core/src/npt/npt.dart:270)
<asynchronous suspension>
#1      main.<anonymous closure> (file:///d:/a/noports/noports/packages/dart/sshnoports/bin/npt.dart:329)
<asynchronous suspension>
#2      main (file:///d:/a/noports/noports/packages/dart/sshnoports/bin/npt.dart:66)
<asynchronous suspension>

PS C:\Users\colin\Downloads\sshnp-windows-x64 (2)\sshnp>
```

### Smartphones

- sshnpd / npt 5.5.0

### Were you using an atApplication when the bug was found?

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by gkc**
Resolves #1182 

**- What I did**
fix: When running npt in keep-alive mode then the keep-alive loop should never exit due to an exception from `npt.run()`

**- How I did it**
Added additional catch clauses to the keep-alive loop, and ensure that they do not lead to the loop terminating if keep-alive is set.

**- How to verify it**
@cconstab please can you test against this branch?

### CODE REVIEW

**Review by xavierchanth — APPROVED** [review]

**Comment by gkc** [comment]
@cconstab have you had a chance to test this?

**Comment by cconstab** [comment]
I will sorry!

**Comment by gkc** [comment]
@cconstab ping

**Review by xavierchanth — APPROVED** [review]

**Comment by gkc** [comment]
Discussed with @XavierChanth - we will merge this PR and come back to the ticket if the problem occurs during subsequent real-world testing

**Pull request merged**
