### PR TITLE
ci: e2e tests timeout max 6 minutes

### PR DESCRIPTION
**Pull request by JeremyTubongbanua**
**- What I did**

- docker services will be max up 6 minutes
- some tests will run forever and never fail
**- How I did it**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by cconstab** [comment]
Does this actually work ? I thought that --timeout only worked in interactive mode ?

**Comment by JeremyTubongbanua** [comment]
> Does this actually work ? I thought that --timeout only worked in interactive mode ?

Possibly, I will double check

**Comment by xavierchanth** [comment]
6 mins is not enough, the sync based ones need ~10 mins

**Comment by xavierchanth** [comment]
I also have a way to improve e2e test time, docker compose has a dependency and healthcheck feature which we can use to have sshnp wait until sshnpd is ready to receive connections (rather than some arbitrary time frame)

**Pull request closed without merging**
