### PR TITLE
chore: release v3.4.0

### PR DESCRIPTION
**Pull request by xavierchanth**
**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**
chore: release v3.4.0

### CODE REVIEW

**Comment by cconstab** [comment]
I see no functional problems in my testing....
sshnp pass
sshnpd pass
sshrv pass
sshrvd pass
at_activate pass

But I do see that sshnpd occasionaly fails with :-
```
Unhandled exception:
SocketException: Connection reset by peer (OS Error: Connection reset by peer, errno = 104), address = 92a7c219-e2eb-5f50-ac23-d7acba106cf5.swarm0002.atsign.zone, port = 57224
```

We might want to address this before release ? @gkc  ?


What is odd is that I have NOT seen sshrvd fail (yet) I will continue soak testing with some expect!......

1 minute later 

```
Unhandled exception:
SocketException: Connection reset by peer (OS Error: Connection reset by peer, errno = 104), address = cb6f2346-fcd0-577e-ae50-30d16faba65f.swarm0002.atsign.zone, port = 50544
```
on sshrvd

**Comment by gkc** [comment]
I've made [this PR](https://github.com/atsign-foundation/at_libraries/pull/379) for a new version of at_lookup to wrap OutboundMessageListener's call to `socket.listen` in a runZonedGuarded block. 

Made [a PR in at_client](https://github.com/atsign-foundation/at_client_sdk/pull/1087) just for test purposes to run all of the at_client test pack with the new version of at_lookup. Tests have passed

@cconstab I'd recommend you do a round of sshnp testing again using a dependency override for at_lookup
```yaml
dependency_overrides:
  at_lookup:
    git:
      url: https://github.com/atsign-foundation/at_libraries.git
      path: packages/at_lookup
      ref: gkc-socket-shenanigans
```

I'm out for the rest of today but assuming testing goes well then @XavierChanth please review / approve the at_lookup PR and then publish the new version (the at_lookup PR includes a CHANGELOG entry and bumps the version to 3.0.38) ... then change the at_lookup version being used by sshnoports to 3.0.38 and we should be good to go for release.

**Comment by cconstab** [comment]
Will do that today!

**Comment by xavierchanth** [comment]
Let's hold off on testing and publishing until #250 / #251 has been addressed

**Comment by JeremyTubongbanua** [comment]
> Let's hold off on testing and publishing until #250 / #251 has been addressed

#250 and #251 have been addressed.

I would recommend pulling from latest trunk to get the latest backwards compatibility tests

**Comment by xavierchanth** [comment]
> > Let's hold off on testing and publishing until #250 / #251 has been addressed
> 
> #250 and #251 have been addressed.
> 
> I would recommend pulling from latest trunk to get the latest backwards compatibility tests

Done

**Comment by gkc** [comment]
@XavierChanth @cconstab do you want to incorporate the latest version of at_lookup?

**Comment by cconstab** [comment]
I certainly do!


Testing so far is juat fine and of course not a single failure this far!

**Comment by cconstab** [comment]
> I've made [this PR](https://github.com/atsign-foundation/at_libraries/pull/379) for a new version of at_lookup to wrap OutboundMessageListener's call to `socket.listen` in a runZonedGuarded block.
> 
> Made [a PR in at_client](https://github.com/atsign-foundation/at_client_sdk/pull/1087) just for test purposes to run all of the at_client test pack with the new version of at_lookup. Tests have passed
> 
> @cconstab I'd recommend you do a round of sshnp testing again using a dependency override for at_lookup
> 
> ```yaml
> dependency_overrides:
>   at_lookup:
>     git:
>       url: https://github.com/atsign-foundation/at_libraries.git
>       path: packages/at_lookup
>       ref: gkc-socket-shenanigans
> ```
> 
> I'm out for the rest of today but assuming testing goes well then @XavierChanth please review / approve the at_lookup PR and then publish the new version (the at_lookup PR includes a CHANGELOG entry and bumps the version to 3.0.38) ... then change the at_lookup version being used by sshnoports to 3.0.38 and we should be good to go for release.

So running tests all day yesterday no errors, but set up a soak test last night and some nice catches...


```
INFO|2023-07-13 03:30:04.286029| sshnpd | sshnpd connected notification sent to:from "@cconstab:c9cebcd9-78f9-466d-b814-dfa56d23bda2.servalan.sshnp@ssh_1 

INFO|2023-07-13 03:30:04.734551|OutboundConnectionImpl|close(): calling socket.destroy() on connection to InternetAddress('35.238.38.90', IPv4):5703 

INFO|2023-07-13 03:30:04.734764|AtLookup|Creating new connection

INFO|2023-07-13 03:30:05.432389|AtLookup|New connection created OK 

INFO|2023-07-13 03:30:05.676265|AtLookup|auth success 

INFO|2023-07-13 03:30:08.583220| sshnpd |SUCCESS:id: ef2e1472-0a7f-4f94-9b6d-0209fb4fb8f3 status: NotificationStatusEnum.delivered for: c9cebcd9-78f9-466d-b814-dfa56d23bda2 

SHOUT|2023-07-13 03:30:23.584348| sshnpd |ssh session complete for: @cconstab session: c9cebcd9-78f9-466d-b814-dfa56d23bda2 

INFO|2023-07-13 04:31:32.759981| sshnpd |Private Key received from @cconstab notification id : d48bac57-5189-4097-8764-b040cc5556e8 

INFO|2023-07-13 04:31:34.841763| sshnpd |ssh Public Key received from @cconstab notification id : 5d6bb441-b9a9-4937-870c-087d731417b4 

INFO|2023-07-13 04:31:35.729482| sshnpd |ssh callback request received from @cconstab notification id : 9c364e2f-5651-4c04-97e8-4b5bf631a290 

INFO|2023-07-13 04:31:35.729602| sshnpd |ssh session started for cconstab to 85.239.53.170 on port 34179 using localhost:42445 on 85.239.53.170

SHOUT|2023-07-13 04:31:35.729633| sshnpd |ssh session started from: @cconstab session: 1418df34-c890-4053-bedc-b9a89183d848

INFO|2023-07-13 04:31:37.477309| sshnpd | sshnpd connected notification sent to:from "@cconstab:1418df34-c890-4053-bedc-b9a89183d848.servalan.sshnp@ssh_1 

INFO|2023-07-13 04:31:37.834833|OutboundConnectionImpl|close(): calling socket.destroy() on connection to InternetAddress('35.202.117.86', IPv4):5703 

INFO|2023-07-13 04:31:37.835031|AtLookup|Creating new connection

INFO|2023-07-13 04:31:38.362189|AtLookup|New connection created OK 

INFO|2023-07-13 04:31:38.584175|AtLookup|auth success 

INFO|2023-07-13 04:31:41.383222| sshnpd |SUCCESS:id: 934ded5b-7098-43f8-8d3b-77c9f85d1e50 status: NotificationStatusEnum.delivered for: 1418df34-c890-4053-bedc-b9a89183d848 

SHOUT|2023-07-13 04:31:56.384254| sshnpd |ssh session complete for: @cconstab session: 1418df34-c890-4053-bedc-b9a89183d848 

INFO|2023-07-13 05:00:09.382770|Monitor (@ssh_1)|socket.listen onDone called. Will destroy socket, set status stopped, call retryCallback 

INFO|2023-07-13 05:00:09.383070|OutboundConnectionImpl|close(): calling socket.destroy() on connection to InternetAddress('34.70.188.187', IPv4):5703

WARNING|2023-07-13 05:00:12.326277|Monitor (@ssh_1)|Heartbeat response not received within expected duration. Heartbeat was sent at 1689249608992, it is now 1689249612326, last heartbeat response was received at 1689249599098. Will close connection, set status stopped, call retryCallback

INFO|2023-07-13 05:00:12.326386|NotificationServiceImpl (@ssh_1)|Monitor retry already queued

INFO|2023-07-13 05:00:14.660401|OutboundConnectionImpl|close(): calling socket.destroy() on connection to InternetAddress('35.238.38.90', IPv4):5703 

INFO|2023-07-13 05:00:14.660494|Monitor (@ssh_1)|socket.listen onDone called. Will destroy socket, set status stopped, call retryCallback

INFO|2023-07-13 05:00:14.660652|Monitor (@ssh_1)|Monitor error Exception: Server is paused : Server is temporarily paused and should be available again shortly - calling the retryCallback

INFO|2023-07-13 05:00:14.660692|NotificationServiceImpl (@ssh_1)|Monitor retry already queued

INFO|2023-07-13 05:00:18.993274|Monitor (@ssh_1)|status is MonitorStatus.errored : heartbeat will not be sent 

INFO|2023-07-13 05:00:20.146040|Monitor (@ssh_1)|socket.listen onDone called. Will destroy socket, set status stopped, call retryCallback 

INFO|2023-07-13 05:00:20.146142|OutboundConnectionImpl|close(): calling socket.destroy() on connection to InternetAddress('35.238.38.90', IPv4):5703

INFO|2023-07-13 05:00:20.146375|Monitor (@ssh_1)|Monitor error Exception: Exception: Server is temporarily paused and should be available again shortly - calling the retryCallback    

INFO|2023-07-13 05:00:20.146415|NotificationServiceImpl (@ssh_1)|Monitor retry already queued

INFO|2023-07-13 05:00:25.485996|Monitor (@ssh_1)|socket.listen onDone called. Will destroy socket, set status stopped, call retryCallback 

INFO|2023-07-13 05:00:25.486084|OutboundConnectionImpl|close(): calling socket.destroy() on connection to InternetAddress('35.238.38.90', IPv4):5703

INFO|2023-07-13 05:00:25.488224|Monitor (@ssh_1)|Monitor error Exception: Exception: Server is temporarily paused and should be available again shortly - calling the retryCallback    

INFO|2023-07-13 05:00:25.488256|NotificationServiceImpl (@ssh_1)|Monitor retry already queued

INFO|2023-07-13 05:00:30.884496|Monitor (@ssh_1)|Monitor error SocketException: Connection refused (OS Error: Connection refused, errno = 111), address = 92a7c219-e2eb-5f50-ac23-d7acba106cf5.swarm0002.atsign.zone, port = 53910 - calling the retryCallback

INFO|2023-07-13 05:00:36.361272|Monitor (@ssh_1)|Monitor error SocketException: Connection refused (OS Error: Connection refused, errno = 111), address = 92a7c219-e2eb-5f50-ac23-d7acba106cf5.swarm0002.atsign.zone, port = 53920 - calling the retryCallback

INFO|2023-07-13 05:00:41.756591|Monitor (@ssh_1)|Monitor error SocketException: Connection refused (OS Error: Connection refused, errno = 111), address = 92a7c219-e2eb-5f50-ac23-d7acba106cf5.swarm0002.atsign.zone, port = 57304 - calling the retryCallback

INFO|2023-07-13 05:00:47.673275|Monitor (@ssh_1)|monitor started for @ssh_1 with last notification time: null 
```

all the time the soak test never failed (I got lucky I guess

```
cconstab@cally:~$ while true; do $(sshnp -f @cconstab -t @ssh_1 -d servalan --host @rv_am -s GitHub_rsa.pub) hostname; date; sleep 3676; done
servalan
Thu Jul 13 05:22:25 AM UTC 2023
servalan
Thu Jul 13 06:23:59 AM UTC 2023
servalan
Thu Jul 13 07:25:32 AM UTC 2023
servalan
Thu Jul 13 08:27:04 AM UTC 2023
servalan
Thu Jul 13 09:28:36 AM UTC 2023
servalan
Thu Jul 13 10:30:10 AM UTC 2023
servalan
Thu Jul 13 11:31:43 AM UTC 2023
servalan
Thu Jul 13 12:33:16 PM UTC 2023
```

Conclusion things are getting caught, things being odd Internet networky stuff ?

**Comment by gkc** [comment]
I think this shows one thing at least, which is that the new at_lookup didn't cause any problems

We'd obviously be happier to see positive proof of fix - ie a warning from the runZonedGuarded block in OutboundMessageListener saying that it actually caught the "reset by peer" exception and was calling onSocketError as that would be proof we had fixed it, but it looks like it didn't occur. Do you recall anything interesting from the last time you saw the uncaught exception? Resuming laptop from sleep, ... ?

**Comment by xavierchanth** [comment]
See #257

**Pull request closed without merging**
