### PR TITLE
refactor: make sshnp more modular

### PR DESCRIPTION
**Pull request by gkc**
**- What I did**
 complete restructuring of sshnp.dart

**- How I did it**
* Split the main into many smaller functions
* Created SSHNP class, making instance variables `final` or `late final` or `late` or just normal volatile instance variables as appropriate
* Documented the SSHNP instance variables and the primary methods (`init()` and `run()`)
* Extracted the SSHNP class to lib/sshnp.dart, leaving just a very short `main()` in bin/sshnp.dart
* Combined utility functions into single new file sshnp_utils.dart
* Added args parsing unit tests

### CODE REVIEW

**Comment by JeremyTubongbanua** [comment]
Testing your branch

**sshnpd**

```
~/.local/bin/sshnpd -a @smoothalligator -m @jeremy_0 -d docker -s -u -v
```

**sshnp**

```
~/.local/bin/sshnp -f @jeremy_0 -t @smoothalligator -d docker -h @rv_am -s id_ed25519.pub -v
```

**ERROR on sshnp**
```
sshnp: connection timeout to sshrvd @rv_am service
```

When switched back to trunk, I no longer get the above error.

**Comment by cconstab** [comment]
While we have the code open.. sshnp shoukd have a -u option to specify the username if the sshnpd was not sharing it. This is a bug/oversight in sshnp right now..

**Comment by JeremyTubongbanua** [comment]
> Testing your branch
> 
> **sshnpd**
> 
> ```
> ~/.local/bin/sshnpd -a @smoothalligator -m @jeremy_0 -d docker -s -u -v
> ```
> 
> **sshnp**
> 
> ```
> ~/.local/bin/sshnp -f @jeremy_0 -t @smoothalligator -d docker -h @rv_am -s id_ed25519.pub -v
> ```
> 
> **ERROR on sshnp**
> 
> ```
> sshnp: connection timeout to sshrvd @rv_am service
> ```
> 
> When switched back to trunk, I no longer get the above error.



Latest commits fixed this issue.

Additional context and proof can be found in the [issue ticket](https://github.com/atsign-foundation/sshnoports/issues/196)

**Comment by gkc** [comment]
I see a LateInitializationError that I need to fix

**Comment by gkc** [comment]
> I see a LateInitializationError that I need to fix

Fixed in latest commit

**Comment by gkc** [comment]
This PR is ready for review and merge, subject to another round of verification testing from @JeremyTubongbanua or @cconstab

**Comment by gkc** [comment]
> While we have the code open.. sshnp shoukd have a -u option to specify the username if the sshnpd was not sharing it. This is a bug/oversight in sshnp right now..

@cconstab Added https://github.com/atsign-foundation/sshnoports/issues/202

**Comment by JeremyTubongbanua** [comment]
@gkc getting these as of commit https://github.com/atsign-foundation/sshnoports/pull/201/commits/5a02053789148a1d2ad7596d18e23a2fcfe4f846

sshnp error

```
Remote sshnpd error: Remote SSH Client failure : SocketException: Failed host lookup: '@rv_am' (OS Error: Name or service not known, errno = -2)
INFO|2023-06-14 01:16:05.008236| sshnp |SUCCESS:id: 3dde7632-0b46-4a04-b80f-76c089cf8bc4 status: NotificationStatusEnum.delivered 37449 22 atsign @rv_am 801f4ff9-fb71-4015-a90a-b28a5c02e5d4 
```

sshnpd error

```
SEVERE|2023-06-14 01:16:04.450863| sshnpd |SSH Client failure : SocketException: Failed host lookup: '@rv_am' (OS Error: Name or service not known, errno = -2) 
```

## sshnp
```sh
atsign@94accbdfd63d:~$ ~/.local/binrefactor/sshnp -f @jeremy_0 -t @smoothalligator -d docker -h @rv_am -s id_ed25519.pub -v
INFO|2023-06-14 01:16:00.735783|AtClientManager|setCurrentAtSign called with atSign @jeremy_0 

INFO|2023-06-14 01:16:00.735822|AtClientManager|Switching atSigns from null to @jeremy_0 

INFO|2023-06-14 01:16:00.737096|HiveBase|commit_log_3c074c7d3712aa56c1d3e81561c463442f282dfda4ddcc62a724ea0844c2f0e0 initialized successfully 

INFO|2023-06-14 01:16:00.737993|HiveBase|3c074c7d3712aa56c1d3e81561c463442f282dfda4ddcc62a724ea0844c2f0e0 initialized successfully 

INFO|2023-06-14 01:16:00.738030|AtClientCommitLogCompaction (@jeremy_0)|Starting commit log compaction job running for every 11 minute(s) 

INFO|2023-06-14 01:16:00.738491|AtClientManager|setCurrentAtSign complete 

INFO|2023-06-14 01:16:00.738523|AtLookup|Creating new connection 

INFO|2023-06-14 01:16:01.258288|AtLookup|New connection created OK 

INFO|2023-06-14 01:16:01.402257|AtLookup|auth success 

INFO|2023-06-14 01:16:01.404670| sshnp |Subscribing to notifications on 801f4ff9-fb71-4015-a90a-b28a5c02e5d4.docker.sshnp@ 

INFO|2023-06-14 01:16:01.678340|Monitor (@jeremy_0)|monitor started for @jeremy_0 with last notification time: null 

INFO|2023-06-14 01:16:01.720694|AbstractAtKeyEncryption (@jeremy_0)|Encrypted shared symmetric key for @jeremy_0 not found in local storage 

INFO|2023-06-14 01:16:01.720725|AbstractAtKeyEncryption (@jeremy_0)|Deleting @rv_am:shared_key@jeremy_0 from LocalSecondary 

INFO|2023-06-14 01:16:01.720829|AbstractAtKeyEncryption (@jeremy_0)|Fetching shared symmetric key for @jeremy_0 from atServer 

INFO|2023-06-14 01:16:01.791019|AbstractAtKeyEncryption (@jeremy_0)|Retrieved my encrypted copy of shared symmetric key for @rv_am from atServer - saving to local storage 

INFO|2023-06-14 01:16:01.793855|AbstractAtKeyEncryption (@jeremy_0)|'Their' copy of shared symmetric key for @rv_am not found in local storage - will check atServer 

INFO|2023-06-14 01:16:01.863674|AbstractAtKeyEncryption (@jeremy_0)|Found 'their' copy of shared symmetric key for @rv_am in atServer - saving to local storage 

INFO|2023-06-14 01:16:02.551375| sshnp |SUCCESS:id: 4ca0828b-b5f2-47c2-ba23-8c11301ab7e3 status: NotificationStatusEnum.delivered @rv_am:docker.sshrvd@jeremy_0 

INFO|2023-06-14 01:16:02.775665|AbstractAtKeyEncryption (@jeremy_0)|Encrypted shared symmetric key for @jeremy_0 not found in local storage 

INFO|2023-06-14 01:16:02.775711|AbstractAtKeyEncryption (@jeremy_0)|Deleting @smoothalligator:shared_key@jeremy_0 from LocalSecondary 

INFO|2023-06-14 01:16:02.775886|AbstractAtKeyEncryption (@jeremy_0)|Fetching shared symmetric key for @jeremy_0 from atServer 

INFO|2023-06-14 01:16:02.832401|AbstractAtKeyEncryption (@jeremy_0)|Retrieved my encrypted copy of shared symmetric key for @smoothalligator from atServer - saving to local storage 

INFO|2023-06-14 01:16:02.835821|AbstractAtKeyEncryption (@jeremy_0)|'Their' copy of shared symmetric key for @smoothalligator not found in local storage - will check atServer 

INFO|2023-06-14 01:16:02.895765|AbstractAtKeyEncryption (@jeremy_0)|Found 'their' copy of shared symmetric key for @smoothalligator in atServer - saving to local storage 

INFO|2023-06-14 01:16:03.584285| sshnp |SUCCESS:id: 9b5bb531-b49a-4302-bbc6-2f0374360449 status: NotificationStatusEnum.delivered 

INFO|2023-06-14 01:16:04.311256| sshnp |SUCCESS:id: 4bf14f0f-9b40-4ab9-a016-37c32421b19d status: NotificationStatusEnum.delivered 

INFO|2023-06-14 01:16:04.648421| sshnp |Received 801f4ff9-fb71-4015-a90a-b28a5c02e5d4 notification 

Remote sshnpd error: Remote SSH Client failure : SocketException: Failed host lookup: '@rv_am' (OS Error: Name or service not known, errno = -2)
INFO|2023-06-14 01:16:05.008236| sshnp |SUCCESS:id: 3dde7632-0b46-4a04-b80f-76c089cf8bc4 status: NotificationStatusEnum.delivered 37449 22 atsign @rv_am 801f4ff9-fb71-4015-a90a-b28a5c02e5d4 

INFO|2023-06-14 01:16:05.008266| sshnp |Tidying up files 


atsign@94accbdfd63d:~$ 
```

## sshnpd

```
atsign@ac634febb318:~/.local/binrefactor$ ~/.local/binrefactor/sshnpd -a @smoothalligator -m @jeremy_0 -d docker -s -u -v
INFO|2023-06-14 01:15:45.293307|AtClientManager|setCurrentAtSign called with atSign @smoothalligator 

INFO|2023-06-14 01:15:45.293345|AtClientManager|Switching atSigns from null to @smoothalligator 

INFO|2023-06-14 01:15:45.294847|HiveBase|commit_log_0fe9fb2745a1a4a3f9c43a7dd8ac860e8291d5bafda9f25df26b45a1ad92726e initialized successfully 

INFO|2023-06-14 01:15:45.326123|HiveBase|0fe9fb2745a1a4a3f9c43a7dd8ac860e8291d5bafda9f25df26b45a1ad92726e initialized successfully 

INFO|2023-06-14 01:15:45.479492|AtClientCommitLogCompaction (@smoothalligator)|Starting commit log compaction job running for every 11 minute(s) 

INFO|2023-06-14 01:15:45.480091|AtClientManager|setCurrentAtSign complete 

INFO|2023-06-14 01:15:45.480104|AtLookup|Creating new connection 

INFO|2023-06-14 01:15:45.892671|AtLookup|New connection created OK 

INFO|2023-06-14 01:15:46.033338|AtLookup|auth success 

INFO|2023-06-14 01:15:47.275259| sshnpd |SUCCESS:id: fd5a2feb-d3f4-46f7-8aa3-a21e20af0b48 status: NotificationStatusEnum.delivered atsign 

WARNING|2023-06-14 01:15:47.298078| sshnpd |connection available 

INFO|2023-06-14 01:15:47.557515|Monitor (@smoothalligator)|monitor started for @smoothalligator with last notification time: null 

INFO|2023-06-14 01:15:49.553127| sshnpd |Private Key received from @jeremy_0 notification id : 0aeed597-7aa4-49ff-9fb4-e9d59274984b 

INFO|2023-06-14 01:15:50.259372| sshnpd |ssh Public Key received from @jeremy_0 notification id : 62cf8a9f-d02f-46e4-91e7-9d98aac2e61d 

INFO|2023-06-14 01:15:50.976935| sshnpd |ssh callback request received from @jeremy_0 notification id : 26c95c34-b833-4c64-a243-6d3ccd43338a 

INFO|2023-06-14 01:15:50.976968| sshnpd |ssh session started for atsign to @rv_am on port 22 using localhost:38549 on @rv_am  

SHOUT|2023-06-14 01:15:50.976973| sshnpd |ssh session started from: @jeremy_0 session: 07d5c23b-be9c-4448-9376-e4a281253c83 

SEVERE|2023-06-14 01:15:50.988248| sshnpd |SSH Client failure : SocketException: Failed host lookup: '@rv_am' (OS Error: Name or service not known, errno = -2) 

INFO|2023-06-14 01:15:51.630554| sshnpd |SUCCESS:id: 9ffa465c-1205-4107-9b04-fa73230278a3 status: NotificationStatusEnum.delivered for: 07d5c23b-be9c-4448-9376-e4a281253c83 

INFO|2023-06-14 01:15:55.025389|AtLookup|Creating new connection 

INFO|2023-06-14 01:15:55.121770|AtLookup|New connection created OK 

INFO|2023-06-14 01:15:55.234881|AtLookup|auth success 

INFO|2023-06-14 01:15:55.281869|SyncService (@smoothalligator)|829651119|Returning serverCommitId 32299 

INFO|2023-06-14 01:15:55.330298|SyncService (@smoothalligator)|829651119|Returning serverCommitId 32299 

INFO|2023-06-14 01:15:55.423574|SyncService (@smoothalligator)|829651119|Inside syncComplete. syncRequest.requestSource : SyncRequestSource.system; syncRequest.onDone : Closure: (SyncResult) => void from Function '_onDone@118025363':. 

INFO|2023-06-14 01:15:55.470403|SyncService (@smoothalligator)|829651119|Returning serverCommitId 32301 

INFO|2023-06-14 01:16:03.023854| sshnpd |Private Key received from @jeremy_0 notification id : 9b5bb531-b49a-4302-bbc6-2f0374360449 

INFO|2023-06-14 01:16:03.733553| sshnpd |ssh Public Key received from @jeremy_0 notification id : 4bf14f0f-9b40-4ab9-a016-37c32421b19d 

INFO|2023-06-14 01:16:04.439899| sshnpd |ssh callback request received from @jeremy_0 notification id : 3dde7632-0b46-4a04-b80f-76c089cf8bc4 

INFO|2023-06-14 01:16:04.439941| sshnpd |ssh session started for atsign to @rv_am on port 22 using localhost:37449 on @rv_am  

SHOUT|2023-06-14 01:16:04.439951| sshnpd |ssh session started from: @jeremy_0 session: 801f4ff9-fb71-4015-a90a-b28a5c02e5d4 

SEVERE|2023-06-14 01:16:04.450863| sshnpd |SSH Client failure : SocketException: Failed host lookup: '@rv_am' (OS Error: Name or service not known, errno = -2) 

INFO|2023-06-14 01:16:05.067265|SyncService (@smoothalligator)|829651119|Returning serverCommitId 32304 

INFO|2023-06-14 01:16:05.069558| sshnpd |SUCCESS:id: 47fa8e4b-d99f-4ae3-8535-804678a6a70f status: NotificationStatusEnum.delivered for: 801f4ff9-fb71-4015-a90a-b28a5c02e5d4 

INFO|2023-06-14 01:16:05.114561|SyncService (@smoothalligator)|829651119|Returning serverCommitId 32304 

INFO|2023-06-14 01:16:05.166655|SyncService (@smoothalligator)|829651119|Inside syncComplete. syncRequest.requestSource : SyncRequestSource.system; syncRequest.onDone : Closure: (SyncResult) => void from Function '_onDone@118025363':. 

INFO|2023-06-14 01:16:05.210296|SyncService (@smoothalligator)|829651119|Returning serverCommitId 32304
```

**Comment by gkc** [comment]
Oh bother, I borked it again. Will fix in the am, it's a sequencing problem I introduced in the commit to fix the late initialization error. I should have just fixed the log messages

**Comment by gkc** [comment]
@JeremyTubongbanua Decided not to wait until the morning. I've fixed that sequencing problem now in https://github.com/atsign-foundation/sshnoports/pull/201/commits/a28c44ff4b4a27a99d2143fcb15a8cecdb099b72

**Comment by JeremyTubongbanua** [comment]
@gkc That worked!

## sshnp

```
atsign@ff8ecc33dd9a:~$ ~/.local/binrefactor/sshnp -f @jeremy_0 -t @smoothalligator -d docker -h @rv_am -s id_ed25519.pub -v
INFO|2023-06-14 01:37:03.375594|AtClientManager|setCurrentAtSign called with atSign @jeremy_0 

INFO|2023-06-14 01:37:03.375657|AtClientManager|Switching atSigns from null to @jeremy_0 

INFO|2023-06-14 01:37:03.378206|HiveBase|commit_log_3c074c7d3712aa56c1d3e81561c463442f282dfda4ddcc62a724ea0844c2f0e0 initialized successfully 

INFO|2023-06-14 01:37:03.379455|HiveBase|3c074c7d3712aa56c1d3e81561c463442f282dfda4ddcc62a724ea0844c2f0e0 initialized successfully 

INFO|2023-06-14 01:37:03.379501|AtClientCommitLogCompaction (@jeremy_0)|Starting commit log compaction job running for every 11 minute(s) 

INFO|2023-06-14 01:37:03.380020|AtClientManager|setCurrentAtSign complete 

INFO|2023-06-14 01:37:03.380071|AtLookup|Creating new connection 

INFO|2023-06-14 01:37:03.718466|AtLookup|New connection created OK 

INFO|2023-06-14 01:37:03.827145|AtLookup|auth success 

INFO|2023-06-14 01:37:03.829797| sshnp |Subscribing to notifications on 4f796586-9e97-457f-a52d-795227df7bb2.docker.sshnp@ 

INFO|2023-06-14 01:37:04.084192|Monitor (@jeremy_0)|monitor started for @jeremy_0 with last notification time: null 

INFO|2023-06-14 01:37:04.084903|AbstractAtKeyEncryption (@jeremy_0)|Encrypted shared symmetric key for @jeremy_0 not found in local storage 

INFO|2023-06-14 01:37:04.084930|AbstractAtKeyEncryption (@jeremy_0)|Deleting @rv_am:shared_key@jeremy_0 from LocalSecondary 

INFO|2023-06-14 01:37:04.085360|AbstractAtKeyEncryption (@jeremy_0)|Fetching shared symmetric key for @jeremy_0 from atServer 

INFO|2023-06-14 01:37:04.129226|AbstractAtKeyEncryption (@jeremy_0)|Retrieved my encrypted copy of shared symmetric key for @rv_am from atServer - saving to local storage 

INFO|2023-06-14 01:37:04.132316|AbstractAtKeyEncryption (@jeremy_0)|'Their' copy of shared symmetric key for @rv_am not found in local storage - will check atServer 

INFO|2023-06-14 01:37:04.178124|AbstractAtKeyEncryption (@jeremy_0)|Found 'their' copy of shared symmetric key for @rv_am in atServer - saving to local storage 

INFO|2023-06-14 01:37:04.859475| sshnp |SUCCESS:id: 258539e1-07d2-4f1a-a65c-0098d7ea1bfd status: NotificationStatusEnum.delivered @rv_am:docker.sshrvd@jeremy_0 

INFO|2023-06-14 01:37:05.064005|AbstractAtKeyEncryption (@jeremy_0)|Encrypted shared symmetric key for @jeremy_0 not found in local storage 

INFO|2023-06-14 01:37:05.064067|AbstractAtKeyEncryption (@jeremy_0)|Deleting @smoothalligator:shared_key@jeremy_0 from LocalSecondary 

INFO|2023-06-14 01:37:05.064425|AbstractAtKeyEncryption (@jeremy_0)|Fetching shared symmetric key for @jeremy_0 from atServer 

INFO|2023-06-14 01:37:05.111610|AbstractAtKeyEncryption (@jeremy_0)|Retrieved my encrypted copy of shared symmetric key for @smoothalligator from atServer - saving to local storage 

INFO|2023-06-14 01:37:05.115649|AbstractAtKeyEncryption (@jeremy_0)|'Their' copy of shared symmetric key for @smoothalligator not found in local storage - will check atServer 

INFO|2023-06-14 01:37:05.159238|AbstractAtKeyEncryption (@jeremy_0)|Found 'their' copy of shared symmetric key for @smoothalligator in atServer - saving to local storage 

INFO|2023-06-14 01:37:05.820267| sshnp |SUCCESS:id: a9a5f696-d412-47c0-8820-296ffe4d5def status: NotificationStatusEnum.delivered 

INFO|2023-06-14 01:37:06.483404| sshnp |SUCCESS:id: 2c08782a-1c11-4c56-b8e0-f18a0ef6fa7e status: NotificationStatusEnum.delivered 

INFO|2023-06-14 01:37:07.143057| sshnp |SUCCESS:id: a8c3a037-a0bb-4e10-8b71-2621f4115999 status: NotificationStatusEnum.delivered 45585 37565 atsign 85.239.53.170 4f796586-9e97-457f-a52d-795227df7bb2 

INFO|2023-06-14 01:37:07.718774| sshnp |Received 4f796586-9e97-457f-a52d-795227df7bb2 notification 

INFO|2023-06-14 01:37:07.718798| sshnp |Session 4f796586-9e97-457f-a52d-795227df7bb2 connected successfully 

INFO|2023-06-14 01:37:07.755129| sshnp |Tidying up files 

ssh -p 45585 atsign@localhost -i /atsign/.ssh/id_ed25519
```

## sshnpd

```
atsign@dcb60f9dba1a:~$ ~/.local/binrefactor/sshnpd -a @smoothalligator -m @jeremy_0 -d docker -s -u -v
INFO|2023-06-14 01:37:01.119676|AtClientManager|setCurrentAtSign called with atSign @smoothalligator 

INFO|2023-06-14 01:37:01.119720|AtClientManager|Switching atSigns from null to @smoothalligator 

INFO|2023-06-14 01:37:01.121463|HiveBase|commit_log_0fe9fb2745a1a4a3f9c43a7dd8ac860e8291d5bafda9f25df26b45a1ad92726e initialized successfully 

INFO|2023-06-14 01:37:01.155246|HiveBase|0fe9fb2745a1a4a3f9c43a7dd8ac860e8291d5bafda9f25df26b45a1ad92726e initialized successfully 

INFO|2023-06-14 01:37:01.325874|AtClientCommitLogCompaction (@smoothalligator)|Starting commit log compaction job running for every 11 minute(s) 

INFO|2023-06-14 01:37:01.326536|AtClientManager|setCurrentAtSign complete 

INFO|2023-06-14 01:37:01.326552|AtLookup|Creating new connection 

INFO|2023-06-14 01:37:01.600400|AtLookup|New connection created OK 

INFO|2023-06-14 01:37:01.709583|AtLookup|auth success 

INFO|2023-06-14 01:37:02.564196| sshnpd |SUCCESS:id: 44880b7b-dced-49ef-8214-aa27e81ec508 status: NotificationStatusEnum.delivered atsign 

WARNING|2023-06-14 01:37:02.580754| sshnpd |connection available 

INFO|2023-06-14 01:37:02.862112|Monitor (@smoothalligator)|monitor started for @smoothalligator with last notification time: null 

INFO|2023-06-14 01:37:05.268475| sshnpd |Private Key received from @jeremy_0 notification id : a9a5f696-d412-47c0-8820-296ffe4d5def 

INFO|2023-06-14 01:37:05.932886| sshnpd |ssh Public Key received from @jeremy_0 notification id : 2c08782a-1c11-4c56-b8e0-f18a0ef6fa7e 

INFO|2023-06-14 01:37:06.583324| sshnpd |ssh callback request received from @jeremy_0 notification id : a8c3a037-a0bb-4e10-8b71-2621f4115999 

INFO|2023-06-14 01:37:06.583370| sshnpd |ssh session started for atsign to 85.239.53.170 on port 37565 using localhost:45585 on 85.239.53.170  

SHOUT|2023-06-14 01:37:06.583383| sshnpd |ssh session started from: @jeremy_0 session: 4f796586-9e97-457f-a52d-795227df7bb2 

INFO|2023-06-14 01:37:07.607521| sshnpd | sshnpd connected notification sent to:from "@jeremy_0:4f796586-9e97-457f-a52d-795227df7bb2.docker.sshnp@smoothalligator 

INFO|2023-06-14 01:37:08.216093| sshnpd |SUCCESS:id: 344346a8-0130-4350-abd8-45dc70358ca5 status: NotificationStatusEnum.delivered for: 4f796586-9e97-457f-a52d-795227df7bb2 

INFO|2023-06-14 01:37:10.017230|AtLookup|Creating new connection 

INFO|2023-06-14 01:37:10.108185|AtLookup|New connection created OK 

INFO|2023-06-14 01:37:10.216936|AtLookup|auth success 

INFO|2023-06-14 01:37:10.264708|SyncService (@smoothalligator)|471298032|Returning serverCommitId 32317 

INFO|2023-06-14 01:37:10.314386|SyncService (@smoothalligator)|471298032|Returning serverCommitId 32317 

INFO|2023-06-14 01:37:10.427787|SyncService (@smoothalligator)|471298032|Inside syncComplete. syncRequest.requestSource : SyncRequestSource.system; syncRequest.onDone : Closure: (SyncResult) => void from Function '_onDone@118025363':. 

INFO|2023-06-14 01:37:10.474376|SyncService (@smoothalligator)|471298032|Returning serverCommitId 32318 
```

Goodnight :)

**Comment by gkc** [comment]
Merged in changes from #208 (thank you @purnimavenkatasubbu)

**Review by cconstab — APPROVED** [review]

**Pull request merged**
