### PR TITLE
fix: Correct handling of mixed-case device names

### LINKED ISSUE #839: sshnp/sshnpd `-d` option does not handle capitalisation of device names
### Describe the bug

If using a `-d` in the sshnpd startup with a Capitalised letter in the device name the daemon does not trigger on an incoming request even if sshnp -d is also capitalized correctly.

### Steps to reproduce

1. First set up sshnpd with a device with a capital letter
2. try connecting with sshnp with the sae device name with capital - error
3. try agian without capital letter on the sshnp side - get a notification of keys but unable to connect
4. Change both sshnpd and sshnp to all lower case and everything works

### Expected behavior

Either Capitalization works and the device arg is case sensitive or not and make clear in documentation. 

### Screenshots

_No response_

### Were you using an atApplication when the bug was found?

_No response_

### Additional context

sshnpd set up with capital letter for sshnpd startup

```
[Unit]
Description=Ssh No Ports Daemon
After=network-online.target

# Make this unit fail if sshd isn't started first
Requisite=sshd.service

# Uncomment the following line to make this unit auto-start sshd if it isn't started
# Requires=sshd.service

[Service]
# TODO : set username
User=cconstab
Type=simple
Restart=always
RestartSec=3

# Uncomment the following line to sleep for 10 seconds before starting up the service
# ExecStartPre=/bin/sleep 10

# TODO : set device_atsign, manager_atsign, device_name
ExecStart=/usr/local/bin/sshnpd -a @ssh_1 -m @cconstab -d 1Beaglec  -v -s -u

[Install]
WantedBy=multi-user.target
```

On sshnpd
```
root@beaglebone:~# systemctl daemon-reload
root@beaglebone:~# sudo systemctl restart sshnpd-cconstab.service
root@beaglebone:~# sudo journalctl -u sshnpd-cconstab.service -f
-- Logs begin at Sun 2024-02-18 00:23:24 UTC. --
Feb 20 01:46:43 beaglebone sshnpd[4406]: INFO|2024-02-20 01:46:43.034433|AtClientCommitLogCompaction (@ssh_1)|Starting commit log compaction job running for every 11 minute(s)
Feb 20 01:46:43 beaglebone sshnpd[4406]: INFO|2024-02-20 01:46:43.046302|AtClientManager|setCurrentAtSign complete
Feb 20 01:46:43 beaglebone sshnpd[4406]: INFO|2024-02-20 01:46:43.623829|AtLookup|Creating new connection
Feb 20 01:46:44 beaglebone sshnpd[4406]: INFO|2024-02-20 01:46:44.169367|AtLookup|New connection created OK
Feb 20 01:46:44 beaglebone sshnpd[4406]: INFO|2024-02-20 01:46:44.426001|AtLookup|auth success
Feb 20 01:46:44 beaglebone sshnpd[4406]: INFO|2024-02-20 01:46:44.596834| sshnpd |Starting heartbeat
Feb 20 01:46:44 beaglebone sshnpd[4406]: INFO|2024-02-20 01:46:44.599381| sshnpd |Subscribing to 1Beaglec\.sshnp@
Feb 20 01:46:44 beaglebone sshnpd[4406]: INFO|2024-02-20 01:46:44.601831| sshnpd |Updating device info for 1Beaglec
Feb 20 01:46:44 beaglebone sshnpd[4406]: INFO|2024-02-20 01:46:44.906300| sshnpd |Done
Feb 20 01:46:45 beaglebone sshnpd[4406]: INFO|2024-02-20 01:46:45.142606|Monitor (@ssh_1)|monitor started for @ssh_1 with last notification time: null
Feb 20 01:47:18 beaglebone sshnpd[4406]: INFO|2024-02-20 01:47:18.719856| sshnpd |Received: sshpublickey
Feb 20 01:47:18 beaglebone sshnpd[4406]: INFO|2024-02-20 01:47:18.724240| sshnpd |ssh Public Key received from @cconstab notification id : 46f15984-a181-4ca6-b42a-e7afdcb15356
```

from the sshnp side

```
cconstab@tarial ~ % sshnp -f @cconstab -t @ssh_1 -d 1Beaglec -h @rv_am  -i ~/.ssh/id_ed25519 -s
2024-02-19 17:47:16.782479 : Resolving remote username for user session
2024-02-19 17:47:17.610567 : Resolving remote username for tunnel session
2024-02-19 17:47:17.611099 : Sharing ssh public key
2024-02-19 17:47:18.392187 : Fetching host and port from srvd
2024-02-19 17:47:20.094069 : Sending session request to the device daemon
2024-02-19 17:47:20.348692 : Waiting for response from the device daemon

Error : No response from the device daemon
cconstab@tarial ~ %
```

Moving to Lower case everything works

```
[Unit]
Description=Ssh No Ports Daemon
After=network-online.target

# Make this unit fail if sshd isn't started first
Requisite=sshd.service

# Uncomment the following line to make this unit auto-start sshd if it isn't started
# Requires=sshd.service

[Service]
# TODO : set username
User=cconstab
Type=simple
Restart=always
RestartSec=3

# Uncomment the following line to sleep for 10 seconds before starting up the service
# ExecStartPre=/bin/sleep 10

# TODO : set device_atsign, manager_atsign, device_name
ExecStart=/usr/local/bin/sshnpd -a @ssh_1 -m @cconstab -d 1beaglec  -v -s -u

[Install]
WantedBy=multi-user.target
```

the sshnpd output

```
root@beaglebone:~# systemctl daemon-reload
root@beaglebone:~# sudo systemctl restart sshnpd-cconstab.service
root@beaglebone:~# sudo journalctl -u sshnpd-cconstab.service -f
-- Logs begin at Sun 2024-02-18 00:23:24 UTC. --
Feb 20 01:51:20 beaglebone sshnpd[4488]: INFO|2024-02-20 01:51:20.915530|AtClientCommitLogCompaction (@ssh_1)|Starting commit log compaction job running for every 11 minute(s)
Feb 20 01:51:20 beaglebone sshnpd[4488]: INFO|2024-02-20 01:51:20.927610|AtClientManager|setCurrentAtSign complete
Feb 20 01:51:21 beaglebone sshnpd[4488]: INFO|2024-02-20 01:51:21.525457|AtLookup|Creating new connection
Feb 20 01:51:22 beaglebone sshnpd[4488]: INFO|2024-02-20 01:51:22.143062|AtLookup|New connection created OK
Feb 20 01:51:22 beaglebone sshnpd[4488]: INFO|2024-02-20 01:51:22.448019|AtLookup|auth success
Feb 20 01:51:22 beaglebone sshnpd[4488]: INFO|2024-02-20 01:51:22.640320| sshnpd |Starting heartbeat
Feb 20 01:51:22 beaglebone sshnpd[4488]: INFO|2024-02-20 01:51:22.642648| sshnpd |Subscribing to 1beaglec\.sshnp@
Feb 20 01:51:22 beaglebone sshnpd[4488]: INFO|2024-02-20 01:51:22.645214| sshnpd |Updating device info for 1beaglec
Feb 20 01:51:22 beaglebone sshnpd[4488]: INFO|2024-02-20 01:51:22.983409| sshnpd |Done
Feb 20 01:51:23 beaglebone sshnpd[4488]: INFO|2024-02-20 01:51:23.208660|Monitor (@ssh_1)|monitor started for @ssh_1 with last notification time: null
Feb 20 01:51:34 beaglebone sshnpd[4488]: INFO|2024-02-20 01:51:34.260233| sshnpd |Received: sshpublickey
Feb 20 01:51:34 beaglebone sshnpd[4488]: INFO|2024-02-20 01:51:34.267917| sshnpd |ssh Public Key received from @cconstab notification id : 9b68e58d-b1a1-4349-8ce2-ea619daff3aa
Feb 20 01:51:35 beaglebone sshnpd[4488]: INFO|2024-02-20 01:51:35.862197| sshnpd |Received: ssh_request
Feb 20 01:51:35 beaglebone sshnpd[4488]: INFO|2024-02-20 01:51:35.867991| sshnpd |>=4.0.0 request for ssh received from @cconstab ( {id: 7cf8e8d7-4b7f-4710-a0f0-e923bab51436, key: @ssh_1:ssh_request.1beaglec.sshnp@cconstab, from: @cconstab, to: @ssh_1, epochMillis: 1708393895463, value: {"payload":{"direct":true,"sessionId":"d2c95989-8ff7-40f0-b3ff-bf38a02c61bd","host":"85.239.53.170","port":42119,"authenticateToRvd":true,"clientNonce":"2024-02-19T17:51:32.379275","rvdNonce":"2024-02-20T01:51:43.698053","encryptRvdTraffic":true,"clientEphemeralPK":"MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAu2LO/RHFdWSpR2wwtvtv+ily5MIIBMxb1LOtu++umCo67NjMwZrfcphwkAScjGee+pUO55LZIiPxyTY33xtI7U7QkTy+u7OlrsUw45CRib/tu3NFwWBx/IFJFut2cGJB2D/RSQy+WyIYcyjwRzqIi/buYJHxRs1Rtj+/QPGY0jgeYyKA/UBqjJZ36ScROIFf3Af5mEg2vyARYN8Off+6i3xw0Do7VD5mwYkcYzOzeQIpcKreg1Xnh5e7vlNDIW0E0VA1kqdGjw5IohOR5lMPv5Axa+pG9n989BKfLKBXncUbqkv5T6uevBHL6J3+tKheLITRAVoWdFy3gqFUB4wfzwIDAQAB","clientEphemeralPKType":"rsa2048"},"signature":"oNZ9W+kzZIQVC2CwaA7uVq8A9pTjwk56zTHDgCUc53yVzyVIPih+gqHQvTvc9ekSMZF55hzwqaerTtnuN+UUbEfPFgwzcoQEHpnyVSOO5UUhTvs1Yb+BTjRmE7cdLmo3PUMq8aWBoqY4o+lPAm4XSsaPljR3Y4U+vq7PVl8wq96DNflt4BR4yYz5bH+6zCFyXc7KWqePDslrW2drkt2XFAeCIbXJBuVA0HVg4yPme182E60fU6WBpJm7HxmhbQGKwUlh6y7Yi0B0VxbfzQhNxrXU5UMCOTvuNCueFqcN3DYGogWj3skfZX1mOSh/t+I27Ay4SyK3xA0/rS3QtNC5Cw==","hashingAlgo":"sha256","signingAlgo":"rsa2048"}, operation: update, messageType: MessageType.key, isEncrypted: true, notificationStatus: , expiresAt: null, metadata: Metadata{ttl: null, ttb: null, ttr: null,ccd: null, isPublic: false, isHidden: false, availableAt : null, expiresAt : null, refreshAt : null, createdAt : null, updatedAt : null, isBinary : false, isEncrypted : false, isCached : false, dataSignature: null, sharedKeyStatus: null, encryptedSharedKey: null, pubKeyCheckSum: null, encoding: null, encKeyName: null, encAlgo: null, ivNonce: hu+t7chFvljNzoK3iDZkxw==, skeEncKeyName: null, skeEncAlgo: null}} )
Feb 20 01:51:35 beaglebone sshnpd[4488]: INFO|2024-02-20 01:51:35.893| sshnpd |Signing Verification Result: ResultType: bool, Result: true, SigningMetadata: {HashingAlgo: sha256, SigningAlgo: rsa2048, SignatureTimestamp: 2024-02-20 01:51:35.883572Z}
Feb 20 01:51:35 beaglebone sshnpd[4488]: INFO|2024-02-20 01:51:35.895805| sshnpd |svr.result is a bool
Feb 20 01:51:35 beaglebone sshnpd[4488]: INFO|2024-02-20 01:51:35.897785| sshnpd |svr.result is true
Feb 20 01:51:35 beaglebone sshnpd[4488]: INFO|2024-02-20 01:51:35.899977| sshnpd |Setting up ports for direct ssh session using openssh (openssh) from: @cconstab session: d2c95989-8ff7-40f0-b3ff-bf38a02c61bd
Feb 20 01:51:36 beaglebone sshnpd[4488]: INFO|2024-02-20 01:51:36.010175|SrvImplExec|SrvImplExec.run(): executing /usr/local/bin/srv -h 85.239.53.170 -p 42119 --local-port 22 --rv-auth --rv-e2ee
Feb 20 01:51:36 beaglebone sshnpd[4488]: INFO|2024-02-20 01:51:36.141531|SrvImplExec|rv stderr | authenticating socketB
Feb 20 01:51:36 beaglebone sshnpd[4488]: INFO|2024-02-20 01:51:36.154132|SrvImplExec|rv stderr | rv started successfully
Feb 20 01:51:36 beaglebone sshnpd[4488]: INFO|2024-02-20 01:51:36.158923|SrvImplExec|rv stderr | Waiting for connector to close
Feb 20 01:51:36 beaglebone sshnpd[4488]: INFO|2024-02-20 01:51:36.159625| sshnpd |Started rv - pid is 4499
```
and the sshnp

```
cconstab@tarial ~ % sshnp -f @cconstab -t @ssh_1 -d 1beaglec -h @rv_am  -i ~/.ssh/id_ed25519 -s
2024-02-19 17:51:32.379950 : Resolving remote username for user session
2024-02-19 17:51:33.239383 : Resolving remote username for tunnel session
2024-02-19 17:51:33.240063 : Sharing ssh public key
2024-02-19 17:51:33.937373 : Fetching host and port from srvd
2024-02-19 17:51:35.310418 : Sending session request to the device daemon
2024-02-19 17:51:35.512224 : Waiting for response from the device daemon
2024-02-19 17:51:37.033205 : Received response from the device daemon
2024-02-19 17:51:37.033499 : Creating connection to socket rendezvous
2024-02-19 17:51:37.106850 : Starting tunnel session
2024-02-19 17:51:37.824226 : Starting user session

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Tue Feb 20 01:51:38 2024 from 127.0.0.1
cconstab@beaglebone:~$
```

### PR DESCRIPTION
**Pull request by gkc**
**- What I did**
- fix: Updated device name validation : now require alphanumeric snake case
- feat: Increased max length of device name to 36
- feat: Use the same device name validation in all relevant constructors
- docs: Updated docs to include device_name constraints (alphanumeric snake case, max length 36)
- resolves #839 

**- How I did it**
- modified regex in validation_utils.dart to be alphanumeric snake case, max length 36
- modified various programs' args parsing to validate device names using the same validation function
- modified various programs' args help to use the same language for describing the device name format
- Added unit tests for invalid device names
- Modified other unit tests to use valid device names

**- How to verify it**
Tests pass

### CODE REVIEW

**Review by cconstab — DISMISSED** [review]

**Comment by gkc** [comment]
- Changed validation regex for device name to alphanumeric snake case, max length 30
- Have all relevant constructors assert valid device name using the same validation function
- Modified installation docs to include device name format info
- Modified various program args to include consistent device name format help

**Review by xavierchanth — DISMISSED** [review]
LGTM.
I had mentioned making it 36 characters so that someone using uuid v4s to manage their devices could do:

sshnpd -d "$(echo $uuid | sed 's/-/_/g')" ...

But this is still better than what we had before. There are some people who may be using uppercase device names as well, so it might be good if sshnpd automatically converts the device name input to lower case and emits a warning. This way upgrading is non-breaking

**Comment by gkc** [comment]
> LGTM. I had mentioned making it 36 characters so that someone using uuid v4s to manage their devices could do:
> 
> sshnpd -d "$(echo $uuid | sed 's/-/_/g')" ...
> 
> But this is still better than what we had before. There are some people who may be using uppercase device names as well, so it might be good if sshnpd automatically converts the device name input to lower case and emits a warning. This way upgrading is non-breaking

Updated to 36 length

Given that the daemon does not currently work properly when using uppercase device names, I'd rather avoid any potential future confusion / bugs and have strict validation requiring lowercase

**Review by cconstab — COMMENTED** [review]
Observation: Connected appears in the command line then an error message. I would have expected syntax to be checked before connection was made. Does not break anything just felt unexpected..
e.g.

```
╰$ ./npt -f @cconstab -t @ssh_1 -d ser-valan -l 9000 -r @rv_am -p 3389                            
Connecting ... Connected
Version : 5.0.3 (core: 6.0.4)
-f, --from (mandatory)                       This client's atSign
-t, --to (mandatory)                         The device daemon's atSign
-r, --srvd (mandatory)                       The socket rendezvous's atSign
-d, --device (mandatory)                     Receiving device name. Alphanumeric snake case, max length 36.
-l, --local-port,--lp                        client-side local port for the socket tunnel. If not supplied, we will
                                             ask the o/s for a spare port
                                             (defaults to "0")
-p, --remote-port,--rp (mandatory)           The remote port required
-h, --remote-host,--rh                       The remote host required
                                             (defaults to "localhost")
-k, --key-file,--keyFile                     Path to this client's atSign's keyFile, if not in ~/.atsign/keys/
    --root-domain                            atDirectory domain
                                             (defaults to "root.atsign.org")
    --[no-]per-session-storage,--[no-]pss    Use ephemeral local storage for each session. Defaults to true,
                                             enabling you to run multiple local clients concurrently. However: if
                                             you wish to run just one client at a time, then you will get a
                                             performance boost if you negate this flag.
                                             (defaults to on)
-v, --verbose                                More logging
    --help                                   Print usage
-x, --output-execution-command               Instead of running the srv in the same process, fork the srv, print
                                             the local port to stdout, and exit this program.

Invalid argument(s): Device name must be alphanumeric snake case, max length 36
2024-02-29 15:52:31.423678 : Cleaning up temporary files
```

**Comment by gkc** [comment]
Yeah that's naff. Will fix

**Comment by gkc** [comment]
>> [cconstab] Observation: Connected appears in the command line then an error message. I would have expected syntax to be checked before connection was made. Does not break anything just felt unexpected

> [gkc] Yeah that's naff. Will fix

@cconstab fixed

**Review by cconstab — APPROVED** [review]

**Pull request merged**
