### PR TITLE
feat: Refactor so that app can be packed with `poetry build` DO NOT MERGE

### PR DESCRIPTION
**Pull request by cpswan**
Rather than have fiddly install instructions it would be better to use Python's packaging tools (e.g. poetry) to package this. That Python package can then be put inside of distro specific packages (e.g. a `.ipk` file that can be installed with `opkg` on OpenWRT).

@XavierChanth @Xlin123 this shouldn't be merged until #445 is resolved, and we should then apply the pattern of changes (rather than specific commits) found here.

**- What I did**

Refactored into a single script.

The other option would be to create an sshnpdpy package, and then another script (in another package) that would call into it, but that's more complexity and a less good user experience.

**- How I did it**

Copied the SSHNPDClient class from a separate lib directory into the (renamed) sshnpdpy.py script

Added a [tool.poetry.scripts] section to `pyproject.toml`, which defines the entry point.

**- How to verify it**

@Xlin123 please try this out (on this branch) to get a feel for how things (will) work.

Run `poetry build`, which will create `sshnpdpy-0.3.0-py3-none-any.whl` in the `dist` directory.

That can then be installed with `pip3 install dist/sshnpdpy-0.3.0-py3-none-any.whl`.

And then run `sshnpdpy`

**- Description for the changelog**

feat: Refactor so that app can be packed with `poetry build`

### CODE REVIEW

**Comment by Xlin123** [comment]
@cpswan  #445 Is resolved, do you want me to make a commit for the merge conflicts?

**Comment by Xlin123** [comment]
@cpswan do you want me to make a commit for the merge conflicts?

**Comment by cpswan** [comment]
@Xlin123 nope. Let's not even try to merge these changes. Please take the pattern of what's been done here and apply it to the present code. Once you have a fresh PR for the refactor I'll close this one. Or if you're not clear about what needs to be done I'm happy to start over with the latest code.

**Comment by Xlin123** [comment]
> @Xlin123 nope. Let's not even try to merge these changes. Please take the pattern of what's been done here and apply it to the present code. Once you have a fresh PR for the refactor I'll close this one. Or if you're not clear about what needs to be done I'm happy to start over with the latest code.

Ok, sounds good! I'll make a new PR for the refactor.

**Comment by cpswan** [comment]
Overtaken by #601

**Pull request closed without merging**
