### PR TITLE
ci: Increase wait times

### PR DESCRIPTION
**Pull request by xavierchanth**
**- What I did**

Default time (i.e. no sync)
7s -> 10s

Sync clients
30s -> 60s

**- How I did it**

**- How to verify it**

**- Description for the changelog**
ci: Increase wait times

### CODE REVIEW

**Review by cpswan — DISMISSED** [review]

**Comment by xavierchanth** [comment]
@gkc @cpswan I'll keep tweaking until I can get 2-3 runs with no fails

**Comment by xavierchanth** [comment]
10s on no sync has passed twice, 60s on the sync clients has passed once, I raised the max-parallel to 100. If this last run of the tests pass then I think we are good.

**Comment by xavierchanth** [comment]
Down to just 1x 10s test failing
Running again

**Comment by JeremyTubongbanua** [comment]
The 10s sleep isn't actually there. the tests without the number at the end aren't sleeping at all at the moment

image

**Comment by xavierchanth** [comment]
> The 10s sleep isn't actually there. the tests without the number at the end aren't sleeping at all at the moment
> 
> image

That's because the 10s is the default fallback value in the composite workflow. i.e. not specifying a time will default to 10s.

**Comment by xavierchanth** [comment]
Oh I see what you mean...

**Comment by xavierchanth** [comment]
CleanShot 2023-08-11 at 13 23 07@2x

Fixed in [1c386ca](https://github.com/atsign-foundation/sshnoports/pull/325/commits/1c386ca2f82e55385a0e66b89af3367ab6011783)

**Review by cpswan — APPROVED** [review]

**Pull request merged**
